// Seed data for The Molecular Sandbox
// Run with: bun run prisma/seed.ts
import { db } from "../src/lib/db";

interface ChemicalSeed {
  name: string;
  formula: string;
  molarMass: number;
  density: number;
  specificHeatCapacity: number;
  surfaceTension: number;
  vaporPressure: number;
  boilingPoint: number;
  meltingPoint: number;
  hexColor: string;
  stateAtSTP: string;
  hazards: string[];
  solubility: Record<string, number>;
  refractiveIndex: number;
  viscosity: number;
  category: string;
  description: string;
}

const chemicals: ChemicalSeed[] = [
  {
    name: "Water",
    formula: "H2O",
    molarMass: 18.015,
    density: 1.0,
    specificHeatCapacity: 4.18,
    surfaceTension: 0.072,
    vaporPressure: 3.17,
    boilingPoint: 100,
    meltingPoint: 0,
    hexColor: "#aaddff",
    stateAtSTP: "liquid",
    hazards: [],
    solubility: {},
    refractiveIndex: 1.33,
    viscosity: 1.0,
    category: "solvent",
    description: "Universal solvent, essential for all aqueous chemistry.",
  },
  {
    name: "Hydrochloric Acid",
    formula: "HCl",
    molarMass: 36.46,
    density: 1.18,
    specificHeatCapacity: 3.14,
    surfaceTension: 0.068,
    vaporPressure: 30,
    boilingPoint: 110,
    meltingPoint: -30,
    hexColor: "#ccffcc",
    stateAtSTP: "liquid",
    hazards: ["corrosive", "toxic", "irritant"],
    solubility: {},
    refractiveIndex: 1.36,
    viscosity: 1.2,
    category: "acid",
    description: "Strong acid, fully dissociates in water.",
  },
  {
    name: "Sodium Hydroxide",
    formula: "NaOH",
    molarMass: 40.0,
    density: 2.13,
    specificHeatCapacity: 1.39,
    surfaceTension: 0.08,
    vaporPressure: 0,
    boilingPoint: 1388,
    meltingPoint: 318,
    hexColor: "#f0f0f0",
    stateAtSTP: "solid",
    hazards: ["corrosive", "irritant"],
    solubility: {},
    refractiveIndex: 1.46,
    viscosity: 0,
    category: "base",
    description: "Strong base, also called lye or caustic soda.",
  },
  {
    name: "Sodium Chloride",
    formula: "NaCl",
    molarMass: 58.44,
    density: 2.16,
    specificHeatCapacity: 0.864,
    surfaceTension: 0.075,
    vaporPressure: 0,
    boilingPoint: 1465,
    meltingPoint: 801,
    hexColor: "#ffffff",
    stateAtSTP: "solid",
    hazards: ["irritant"],
    solubility: {},
    refractiveIndex: 1.54,
    viscosity: 0,
    category: "salt",
    description: "Common table salt, neutral pH in solution.",
  },
  {
    name: "Copper Sulfate",
    formula: "CuSO4",
    molarMass: 159.61,
    density: 3.6,
    specificHeatCapacity: 0.6,
    surfaceTension: 0.075,
    vaporPressure: 0,
    boilingPoint: 650,
    meltingPoint: 200,
    hexColor: "#2244ff",
    stateAtSTP: "solid",
    hazards: ["toxic", "irritant", "environmental"],
    solubility: {},
    refractiveIndex: 1.55,
    viscosity: 0,
    category: "salt",
    description: "Blue crystalline salt, forms bright blue aqueous solutions.",
  },
  {
    name: "Iron",
    formula: "Fe",
    molarMass: 55.845,
    density: 7.87,
    specificHeatCapacity: 0.449,
    surfaceTension: 0,
    vaporPressure: 0,
    boilingPoint: 2862,
    meltingPoint: 1538,
    hexColor: "#888888",
    stateAtSTP: "solid",
    hazards: ["flammable"],
    solubility: {},
    refractiveIndex: 1.0,
    viscosity: 0,
    category: "metal",
    description: "Common metal, reacts with acids to produce hydrogen gas.",
  },
  {
    name: "Hydrogen Peroxide",
    formula: "H2O2",
    molarMass: 34.01,
    density: 1.45,
    specificHeatCapacity: 2.62,
    surfaceTension: 0.075,
    vaporPressure: 2.3,
    boilingPoint: 150,
    meltingPoint: -0.43,
    hexColor: "#aaddff",
    stateAtSTP: "liquid",
    hazards: ["oxidizing", "corrosive"],
    solubility: {},
    refractiveIndex: 1.41,
    viscosity: 1.25,
    category: "oxidizer",
    description: "Decomposes to water and oxygen, catalyzed by MnO2.",
  },
  {
    name: "Potassium Iodide",
    formula: "KI",
    molarMass: 166.0,
    density: 3.12,
    specificHeatCapacity: 0.54,
    surfaceTension: 0.073,
    vaporPressure: 0,
    boilingPoint: 1330,
    meltingPoint: 681,
    hexColor: "#ffffff",
    stateAtSTP: "solid",
    hazards: ["irritant"],
    solubility: {},
    refractiveIndex: 1.51,
    viscosity: 0,
    category: "salt",
    description: "White salt, source of iodide ions for precipitation reactions.",
  },
  {
    name: "Lead Nitrate",
    formula: "Pb(NO3)2",
    molarMass: 331.2,
    density: 4.53,
    specificHeatCapacity: 0.5,
    surfaceTension: 0.075,
    vaporPressure: 0,
    boilingPoint: 470,
    meltingPoint: 270,
    hexColor: "#ffffff",
    stateAtSTP: "solid",
    hazards: ["toxic", "health_hazard", "environmental"],
    solubility: {},
    refractiveIndex: 1.6,
    viscosity: 0,
    category: "salt",
    description: "Toxic salt, forms bright yellow PbI2 precipitate with KI.",
  },
  {
    name: "Lead Iodide",
    formula: "PbI2",
    molarMass: 461.0,
    density: 6.16,
    specificHeatCapacity: 0.4,
    surfaceTension: 0.075,
    vaporPressure: 0,
    boilingPoint: 872,
    meltingPoint: 410,
    hexColor: "#ffdd00",
    stateAtSTP: "solid",
    hazards: ["toxic", "health_hazard"],
    solubility: {},
    refractiveIndex: 1.7,
    viscosity: 0,
    category: "salt",
    description: "Golden yellow precipitate, the classic 'golden rain' reaction.",
  },
  {
    name: "Magnesium",
    formula: "Mg",
    molarMass: 24.305,
    density: 1.74,
    specificHeatCapacity: 1.02,
    surfaceTension: 0,
    vaporPressure: 0,
    boilingPoint: 1090,
    meltingPoint: 650,
    hexColor: "#cccccc",
    stateAtSTP: "solid",
    hazards: ["flammable"],
    solubility: {},
    refractiveIndex: 1.0,
    viscosity: 0,
    category: "metal",
    description: "Lightweight metal, reacts vigorously with acids.",
  },
  {
    name: "Zinc",
    formula: "Zn",
    molarMass: 65.38,
    density: 7.14,
    specificHeatCapacity: 0.388,
    surfaceTension: 0,
    vaporPressure: 0,
    boilingPoint: 907,
    meltingPoint: 420,
    hexColor: "#aaaaaa",
    stateAtSTP: "solid",
    hazards: ["flammable"],
    solubility: {},
    refractiveIndex: 1.0,
    viscosity: 0,
    category: "metal",
    description: "Reactive metal, produces hydrogen gas with acids.",
  },
  {
    name: "Sodium Bicarbonate",
    formula: "NaHCO3",
    molarMass: 84.01,
    density: 2.2,
    specificHeatCapacity: 1.02,
    surfaceTension: 0.075,
    vaporPressure: 0,
    boilingPoint: 333,
    meltingPoint: 50,
    hexColor: "#ffffff",
    stateAtSTP: "solid",
    hazards: ["irritant"],
    solubility: {},
    refractiveIndex: 1.5,
    viscosity: 0,
    category: "salt",
    description: "Baking soda, fizzes with acids producing CO2.",
  },
  {
    name: "Calcium Carbonate",
    formula: "CaCO3",
    molarMass: 100.09,
    density: 2.71,
    specificHeatCapacity: 0.83,
    surfaceTension: 0.075,
    vaporPressure: 0,
    boilingPoint: 825,
    meltingPoint: 825,
    hexColor: "#ffffff",
    stateAtSTP: "solid",
    hazards: ["irritant"],
    solubility: {},
    refractiveIndex: 1.59,
    viscosity: 0,
    category: "salt",
    description: "Chalk/limestone, dissolves in acid with effervescence.",
  },
  {
    name: "Sulfuric Acid",
    formula: "H2SO4",
    molarMass: 98.08,
    density: 1.84,
    specificHeatCapacity: 1.38,
    surfaceTension: 0.075,
    vaporPressure: 0.001,
    boilingPoint: 337,
    meltingPoint: 10,
    hexColor: "#ffffcc",
    stateAtSTP: "liquid",
    hazards: ["corrosive", "toxic", "oxidizing"],
    solubility: {},
    refractiveIndex: 1.42,
    viscosity: 24.5,
    category: "acid",
    description: "Strong diprotic acid, highly exothermic when diluted.",
  },
  {
    name: "Nitric Acid",
    formula: "HNO3",
    molarMass: 63.01,
    density: 1.51,
    specificHeatCapacity: 1.72,
    surfaceTension: 0.075,
    vaporPressure: 6.4,
    boilingPoint: 83,
    meltingPoint: -42,
    hexColor: "#ccffee",
    stateAtSTP: "liquid",
    hazards: ["corrosive", "toxic", "oxidizing"],
    solubility: {},
    refractiveIndex: 1.4,
    viscosity: 0.9,
    category: "acid",
    description: "Strong oxidizing acid, fumes in moist air.",
  },
  {
    name: "Ethanol",
    formula: "C2H5OH",
    molarMass: 46.07,
    density: 0.789,
    specificHeatCapacity: 2.44,
    surfaceTension: 0.022,
    vaporPressure: 5.95,
    boilingPoint: 78.37,
    meltingPoint: -114,
    hexColor: "#ffe8cc",
    stateAtSTP: "liquid",
    hazards: ["flammable"],
    solubility: {},
    refractiveIndex: 1.36,
    viscosity: 1.07,
    category: "organic",
    description: "Common alcohol solvent, highly flammable.",
  },
  {
    name: "Acetic Acid",
    formula: "CH3COOH",
    molarMass: 60.05,
    density: 1.05,
    specificHeatCapacity: 2.04,
    surfaceTension: 0.027,
    vaporPressure: 1.5,
    boilingPoint: 118,
    meltingPoint: 17,
    hexColor: "#ffeecc",
    stateAtSTP: "liquid",
    hazards: ["corrosive", "flammable"],
    solubility: {},
    refractiveIndex: 1.37,
    viscosity: 1.22,
    category: "acid",
    description: "Weak acid, vinegar's main component.",
  },
  {
    name: "Ammonia",
    formula: "NH3",
    molarMass: 17.03,
    density: 0.91,
    specificHeatCapacity: 4.7,
    surfaceTension: 0.021,
    vaporPressure: 857,
    boilingPoint: -33,
    meltingPoint: -78,
    hexColor: "#eeddff",
    stateAtSTP: "liquid",
    hazards: ["corrosive", "toxic", "gas_under_pressure"],
    solubility: {},
    refractiveIndex: 1.33,
    viscosity: 0.25,
    category: "base",
    description: "Aqueous ammonia solution, pungent smell.",
  },
  {
    name: "Sodium Carbonate",
    formula: "Na2CO3",
    molarMass: 105.99,
    density: 2.54,
    specificHeatCapacity: 1.1,
    surfaceTension: 0.075,
    vaporPressure: 0,
    boilingPoint: 1600,
    meltingPoint: 851,
    hexColor: "#ffffff",
    stateAtSTP: "solid",
    hazards: ["irritant"],
    solubility: {},
    refractiveIndex: 1.5,
    viscosity: 0,
    category: "salt",
    description: "Washing soda, weak base in solution.",
  },
  {
    name: "Copper",
    formula: "Cu",
    molarMass: 63.546,
    density: 8.96,
    specificHeatCapacity: 0.385,
    surfaceTension: 0,
    vaporPressure: 0,
    boilingPoint: 2562,
    meltingPoint: 1085,
    hexColor: "#b87333",
    stateAtSTP: "solid",
    hazards: ["irritant"],
    solubility: {},
    refractiveIndex: 1.0,
    viscosity: 0,
    category: "metal",
    description: "Reddish metal, less reactive than hydrogen.",
  },
  {
    name: "Silver Nitrate",
    formula: "AgNO3",
    molarMass: 169.87,
    density: 4.35,
    specificHeatCapacity: 0.4,
    surfaceTension: 0.075,
    vaporPressure: 0,
    boilingPoint: 444,
    meltingPoint: 209,
    hexColor: "#ffffff",
    stateAtSTP: "solid",
    hazards: ["corrosive", "toxic", "environmental"],
    solubility: {},
    refractiveIndex: 1.6,
    viscosity: 0,
    category: "salt",
    description: "Light-sensitive salt, used in displacement reactions.",
  },
  {
    name: "Copper Nitrate",
    formula: "Cu(NO3)2",
    molarMass: 187.56,
    density: 2.32,
    specificHeatCapacity: 0.6,
    surfaceTension: 0.075,
    vaporPressure: 0,
    boilingPoint: 170,
    meltingPoint: 115,
    hexColor: "#00aaff",
    stateAtSTP: "solid",
    hazards: ["irritant", "oxidizing"],
    solubility: {},
    refractiveIndex: 1.55,
    viscosity: 0,
    category: "salt",
    description: "Blue salt, formed when copper displaces silver.",
  },
  {
    name: "Silver",
    formula: "Ag",
    molarMass: 107.87,
    density: 10.49,
    specificHeatCapacity: 0.235,
    surfaceTension: 0,
    vaporPressure: 0,
    boilingPoint: 2162,
    meltingPoint: 962,
    hexColor: "#c0c0c0",
    stateAtSTP: "solid",
    hazards: [],
    solubility: {},
    refractiveIndex: 1.0,
    viscosity: 0,
    category: "metal",
    description: "Precious metal, displaced from solution by copper.",
  },
  {
    name: "Copper Hydroxide",
    formula: "Cu(OH)2",
    molarMass: 97.56,
    density: 3.37,
    specificHeatCapacity: 0.6,
    surfaceTension: 0.075,
    vaporPressure: 0,
    boilingPoint: 800,
    meltingPoint: 80,
    hexColor: "#3399ff",
    stateAtSTP: "solid",
    hazards: ["irritant"],
    solubility: {},
    refractiveIndex: 1.6,
    viscosity: 0,
    category: "salt",
    description: "Blue gelatinous precipitate.",
  },
  {
    name: "Sodium Sulfate",
    formula: "Na2SO4",
    molarMass: 142.04,
    density: 2.66,
    specificHeatCapacity: 1.0,
    surfaceTension: 0.075,
    vaporPressure: 0,
    boilingPoint: 1429,
    meltingPoint: 884,
    hexColor: "#ffffff",
    stateAtSTP: "solid",
    hazards: ["irritant"],
    solubility: {},
    refractiveIndex: 1.5,
    viscosity: 0,
    category: "salt",
    description: "Neutral salt, byproduct of acid-base reactions.",
  },
  {
    name: "Potassium Nitrate",
    formula: "KNO3",
    molarMass: 101.1,
    density: 2.11,
    specificHeatCapacity: 0.95,
    surfaceTension: 0.075,
    vaporPressure: 0,
    boilingPoint: 400,
    meltingPoint: 334,
    hexColor: "#ffffff",
    stateAtSTP: "solid",
    hazards: ["oxidizing"],
    solubility: {},
    refractiveIndex: 1.5,
    viscosity: 0,
    category: "salt",
    description: "Saltpeter, strong oxidizer.",
  },
  {
    name: "Magnesium Chloride",
    formula: "MgCl2",
    molarMass: 95.21,
    density: 2.32,
    specificHeatCapacity: 0.7,
    surfaceTension: 0.075,
    vaporPressure: 0,
    boilingPoint: 1412,
    meltingPoint: 714,
    hexColor: "#ffffff",
    stateAtSTP: "solid",
    hazards: ["irritant"],
    solubility: {},
    refractiveIndex: 1.5,
    viscosity: 0,
    category: "salt",
    description: "Salt formed when magnesium reacts with HCl.",
  },
  {
    name: "Zinc Chloride",
    formula: "ZnCl2",
    molarMass: 136.32,
    density: 2.91,
    specificHeatCapacity: 0.6,
    surfaceTension: 0.075,
    vaporPressure: 0,
    boilingPoint: 732,
    meltingPoint: 293,
    hexColor: "#ffffff",
    stateAtSTP: "solid",
    hazards: ["corrosive", "irritant"],
    solubility: {},
    refractiveIndex: 1.5,
    viscosity: 0,
    category: "salt",
    description: "Salt formed when zinc reacts with HCl.",
  },
  {
    name: "Calcium Chloride",
    formula: "CaCl2",
    molarMass: 110.98,
    density: 2.15,
    specificHeatCapacity: 0.74,
    surfaceTension: 0.075,
    vaporPressure: 0,
    boilingPoint: 1935,
    meltingPoint: 772,
    hexColor: "#ffffff",
    stateAtSTP: "solid",
    hazards: ["irritant"],
    solubility: {},
    refractiveIndex: 1.5,
    viscosity: 0,
    category: "salt",
    description: "Salt formed when calcium carbonate reacts with HCl.",
  },
  {
    name: "Carbon Dioxide",
    formula: "CO2",
    molarMass: 44.01,
    density: 0.00198,
    specificHeatCapacity: 0.84,
    surfaceTension: 0,
    vaporPressure: 101.3,
    boilingPoint: -78.5,
    meltingPoint: -56.6,
    hexColor: "#eeffee",
    stateAtSTP: "gas",
    hazards: ["gas_under_pressure"],
    solubility: {},
    refractiveIndex: 1.0,
    viscosity: 0.015,
    category: "gas",
    description: "Gas produced when carbonates react with acids.",
  },
  {
    name: "Oxygen",
    formula: "O2",
    molarMass: 31.998,
    density: 0.00143,
    specificHeatCapacity: 0.92,
    surfaceTension: 0,
    vaporPressure: 101.3,
    boilingPoint: -183,
    meltingPoint: -218,
    hexColor: "#eeffff",
    stateAtSTP: "gas",
    hazards: ["oxidizing", "gas_under_pressure"],
    solubility: {},
    refractiveIndex: 1.0,
    viscosity: 0.02,
    category: "gas",
    description: "Gas produced by decomposition of hydrogen peroxide.",
  },
  {
    name: "Hydrogen",
    formula: "H2",
    molarMass: 2.016,
    density: 0.00009,
    specificHeatCapacity: 14.3,
    surfaceTension: 0,
    vaporPressure: 101.3,
    boilingPoint: -253,
    meltingPoint: -259,
    hexColor: "#ffeeee",
    stateAtSTP: "gas",
    hazards: ["flammable", "gas_under_pressure"],
    solubility: {},
    refractiveIndex: 1.0,
    viscosity: 0.009,
    category: "gas",
    description: "Highly flammable gas, produced by metal-acid reactions.",
  },
  {
    name: "Manganese Dioxide",
    formula: "MnO2",
    molarMass: 86.94,
    density: 5.03,
    specificHeatCapacity: 0.55,
    surfaceTension: 0.075,
    vaporPressure: 0,
    boilingPoint: 535,
    meltingPoint: 530,
    hexColor: "#333333",
    stateAtSTP: "solid",
    hazards: ["harmful", "health_hazard"],
    solubility: {},
    refractiveIndex: 1.7,
    viscosity: 0,
    category: "reagent",
    description: "Black catalyst, accelerates H2O2 decomposition.",
  },
  {
    name: "Water (Liquid)",
    formula: "H2O(l)",
    molarMass: 18.015,
    density: 1.0,
    specificHeatCapacity: 4.18,
    surfaceTension: 0.072,
    vaporPressure: 3.17,
    boilingPoint: 100,
    meltingPoint: 0,
    hexColor: "#aaddff",
    stateAtSTP: "liquid",
    hazards: [],
    solubility: {},
    refractiveIndex: 1.33,
    viscosity: 1.0,
    category: "solvent",
    description: "Water produced as a reaction product.",
  },
  {
    name: "Iron Sulfate",
    formula: "FeSO4",
    molarMass: 151.91,
    density: 2.84,
    specificHeatCapacity: 0.6,
    surfaceTension: 0.075,
    vaporPressure: 0,
    boilingPoint: 680,
    meltingPoint: 400,
    hexColor: "#88aa44",
    stateAtSTP: "solid",
    hazards: ["irritant"],
    solubility: {},
    refractiveIndex: 1.5,
    viscosity: 0,
    category: "salt",
    description: "Pale green salt, formed when iron displaces copper.",
  },
  {
    name: "Barium Chloride",
    formula: "BaCl2",
    molarMass: 208.23,
    density: 3.86,
    specificHeatCapacity: 0.4,
    surfaceTension: 0.075,
    vaporPressure: 0,
    boilingPoint: 1560,
    meltingPoint: 962,
    hexColor: "#ffffff",
    stateAtSTP: "solid",
    hazards: ["toxic", "health_hazard"],
    solubility: {},
    refractiveIndex: 1.5,
    viscosity: 0,
    category: "salt",
    description: "Toxic salt, used to test for sulfate ions.",
  },
  {
    name: "Barium Sulfate",
    formula: "BaSO4",
    molarMass: 233.39,
    density: 4.5,
    specificHeatCapacity: 0.45,
    surfaceTension: 0.075,
    vaporPressure: 0,
    boilingPoint: 1600,
    meltingPoint: 1580,
    hexColor: "#ffffff",
    stateAtSTP: "solid",
    hazards: ["harmful"],
    solubility: {},
    refractiveIndex: 1.55,
    viscosity: 0,
    category: "salt",
    description: "Insoluble white precipitate, used in medical imaging.",
  },
  {
    name: "Ammonium Chloride",
    formula: "NH4Cl",
    molarMass: 53.49,
    density: 1.53,
    specificHeatCapacity: 1.0,
    surfaceTension: 0.075,
    vaporPressure: 0.1,
    boilingPoint: 338,
    meltingPoint: 338,
    hexColor: "#ffffff",
    stateAtSTP: "solid",
    hazards: ["irritant", "harmful"],
    solubility: {},
    refractiveIndex: 1.5,
    viscosity: 0,
    category: "salt",
    description: "White fumes formed when ammonia meets HCl gas.",
  },
  {
    name: "Potassium Permanganate",
    formula: "KMnO4",
    molarMass: 158.03,
    density: 2.7,
    specificHeatCapacity: 0.6,
    surfaceTension: 0.075,
    vaporPressure: 0,
    boilingPoint: 240,
    meltingPoint: 240,
    hexColor: "#8800cc",
    stateAtSTP: "solid",
    hazards: ["oxidizing", "harmful", "environmental"],
    solubility: {},
    refractiveIndex: 1.6,
    viscosity: 0,
    category: "oxidizer",
    description: "Deep purple oxidizer, decomposes on heating.",
  },
  {
    name: "Potassium Manganate",
    formula: "K2MnO4",
    molarMass: 197.13,
    density: 2.3,
    specificHeatCapacity: 0.6,
    surfaceTension: 0.075,
    vaporPressure: 0,
    boilingPoint: 190,
    meltingPoint: 190,
    hexColor: "#446600",
    stateAtSTP: "solid",
    hazards: ["irritant"],
    solubility: {},
    refractiveIndex: 1.55,
    viscosity: 0,
    category: "salt",
    description: "Green salt, product of KMnO4 decomposition.",
  },
  {
    name: "Cobalt Chloride",
    formula: "CoCl2",
    molarMass: 129.84,
    density: 3.36,
    specificHeatCapacity: 0.6,
    surfaceTension: 0.075,
    vaporPressure: 0,
    boilingPoint: 1049,
    meltingPoint: 735,
    hexColor: "#ff88aa",
    stateAtSTP: "solid",
    hazards: ["toxic", "health_hazard", "environmental"],
    solubility: {},
    refractiveIndex: 1.6,
    viscosity: 0,
    category: "salt",
    description: "Pink hydrated / blue anhydrous — humidity indicator.",
  },
];

interface ReactionSeed {
  name: string;
  equation: string;
  deltaH: number;
  reactionType: string;
  isReversible: boolean;
  conditions: Record<string, unknown>;
  description: string;
  reactants: { name: string; coefficient: number; isLimiting?: boolean }[];
  products: { name: string; coefficient: number }[];
}

const reactions: ReactionSeed[] = [
  {
    name: "Neutralization",
    equation: "NaOH + HCl → NaCl + H2O",
    deltaH: -57.3,
    reactionType: "acid_base",
    isReversible: false,
    conditions: {},
    description: "Classic strong acid + strong base neutralization.",
    reactants: [
      { name: "Sodium Hydroxide", coefficient: 1 },
      { name: "Hydrochloric Acid", coefficient: 1 },
    ],
    products: [
      { name: "Sodium Chloride", coefficient: 1 },
      { name: "Water (Liquid)", coefficient: 1 },
    ],
  },
  {
    name: "Copper Sulfate Precipitation",
    equation: "CuSO4 + 2NaOH → Cu(OH)2↓ + Na2SO4",
    deltaH: -59.8,
    reactionType: "precipitation",
    isReversible: false,
    conditions: {},
    description: "Blue gelatinous precipitate of copper hydroxide.",
    reactants: [
      { name: "Copper Sulfate", coefficient: 1 },
      { name: "Sodium Hydroxide", coefficient: 2 },
    ],
    products: [
      { name: "Copper Hydroxide", coefficient: 1 },
      { name: "Sodium Sulfate", coefficient: 1 },
    ],
  },
  {
    name: "Hydrogen Peroxide Decomposition",
    equation: "2H2O2 →(MnO2) 2H2O + O2↑",
    deltaH: -196,
    reactionType: "decomposition",
    isReversible: false,
    conditions: { catalyst: "MnO2" },
    description: "Catalyzed decomposition producing oxygen gas.",
    reactants: [{ name: "Hydrogen Peroxide", coefficient: 2 }],
    products: [
      { name: "Water (Liquid)", coefficient: 2 },
      { name: "Oxygen", coefficient: 1 },
    ],
  },
  {
    name: "Golden Rain",
    equation: "2KI + Pb(NO3)2 → 2KNO3 + PbI2↓",
    deltaH: -52,
    reactionType: "precipitation",
    isReversible: false,
    conditions: {},
    description: "Brilliant yellow precipitate of lead iodide.",
    reactants: [
      { name: "Potassium Iodide", coefficient: 2 },
      { name: "Lead Nitrate", coefficient: 1 },
    ],
    products: [
      { name: "Potassium Nitrate", coefficient: 2 },
      { name: "Lead Iodide", coefficient: 1 },
    ],
  },
  {
    name: "Baking Soda + Acid",
    equation: "NaHCO3 + HCl → NaCl + H2O + CO2↑",
    deltaH: -11.8,
    reactionType: "acid_base",
    isReversible: false,
    conditions: {},
    description: "Effervescence of carbon dioxide gas.",
    reactants: [
      { name: "Sodium Bicarbonate", coefficient: 1 },
      { name: "Hydrochloric Acid", coefficient: 1 },
    ],
    products: [
      { name: "Sodium Chloride", coefficient: 1 },
      { name: "Water (Liquid)", coefficient: 1 },
      { name: "Carbon Dioxide", coefficient: 1 },
    ],
  },
  {
    name: "Magnesium + Acid",
    equation: "Mg + 2HCl → MgCl2 + H2↑",
    deltaH: -466,
    reactionType: "single_replacement",
    isReversible: false,
    conditions: {},
    description: "Vigorous reaction producing flammable hydrogen gas.",
    reactants: [
      { name: "Magnesium", coefficient: 1 },
      { name: "Hydrochloric Acid", coefficient: 2 },
    ],
    products: [
      { name: "Magnesium Chloride", coefficient: 1 },
      { name: "Hydrogen", coefficient: 1 },
    ],
  },
  {
    name: "Zinc + Acid",
    equation: "Zn + 2HCl → ZnCl2 + H2↑",
    deltaH: -152,
    reactionType: "single_replacement",
    isReversible: false,
    conditions: {},
    description: "Steady production of hydrogen gas bubbles.",
    reactants: [
      { name: "Zinc", coefficient: 1 },
      { name: "Hydrochloric Acid", coefficient: 2 },
    ],
    products: [
      { name: "Zinc Chloride", coefficient: 1 },
      { name: "Hydrogen", coefficient: 1 },
    ],
  },
  {
    name: "Limestone + Acid",
    equation: "CaCO3 + 2HCl → CaCl2 + H2O + CO2↑",
    deltaH: -12,
    reactionType: "acid_base",
    isReversible: false,
    conditions: {},
    description: "Chalk dissolves with fizzing — CO2 evolution.",
    reactants: [
      { name: "Calcium Carbonate", coefficient: 1 },
      { name: "Hydrochloric Acid", coefficient: 2 },
    ],
    products: [
      { name: "Calcium Chloride", coefficient: 1 },
      { name: "Water (Liquid)", coefficient: 1 },
      { name: "Carbon Dioxide", coefficient: 1 },
    ],
  },
  {
    name: "Silver Tree",
    equation: "2AgNO3 + Cu → Cu(NO3)2 + 2Ag",
    deltaH: -147,
    reactionType: "single_replacement",
    isReversible: false,
    conditions: {},
    description: "Silver crystals grow on copper — beautiful displacement.",
    reactants: [
      { name: "Silver Nitrate", coefficient: 2 },
      { name: "Copper", coefficient: 1 },
    ],
    products: [
      { name: "Copper Nitrate", coefficient: 1 },
      { name: "Silver", coefficient: 2 },
    ],
  },
  {
    name: "Iron + Copper Sulfate",
    equation: "Fe + CuSO4 → FeSO4 + Cu",
    deltaH: -156,
    reactionType: "single_replacement",
    isReversible: false,
    conditions: {},
    description: "Iron displaces copper, solution fades from blue to green.",
    reactants: [
      { name: "Iron", coefficient: 1 },
      { name: "Copper Sulfate", coefficient: 1 },
    ],
    products: [
      { name: "Iron Sulfate", coefficient: 1 },
      { name: "Copper", coefficient: 1 },
    ],
  },
  {
    name: "Sulfate Test",
    equation: "BaCl2 + Na2SO4 → BaSO4↓ + 2NaCl",
    deltaH: -6.3,
    reactionType: "precipitation",
    isReversible: false,
    conditions: {},
    description: "White precipitate confirms sulfate presence.",
    reactants: [
      { name: "Barium Chloride", coefficient: 1 },
      { name: "Sodium Sulfate", coefficient: 1 },
    ],
    products: [
      { name: "Barium Sulfate", coefficient: 1 },
      { name: "Sodium Chloride", coefficient: 1 },
    ],
  },
  {
    name: "Ammonia + HCl",
    equation: "NH3 + HCl → NH4Cl",
    deltaH: -176,
    reactionType: "synthesis",
    isReversible: false,
    conditions: {},
    description: "White fumes of ammonium chloride.",
    reactants: [
      { name: "Ammonia", coefficient: 1 },
      { name: "Hydrochloric Acid", coefficient: 1 },
    ],
    products: [{ name: "Ammonium Chloride", coefficient: 1 }],
  },
  {
    name: "Carbonate + Acid",
    equation: "Na2CO3 + 2HCl → 2NaCl + H2O + CO2↑",
    deltaH: -11.3,
    reactionType: "acid_base",
    isReversible: false,
    conditions: {},
    description: "Soda ash reacts with acid — effervescence.",
    reactants: [
      { name: "Sodium Carbonate", coefficient: 1 },
      { name: "Hydrochloric Acid", coefficient: 2 },
    ],
    products: [
      { name: "Sodium Chloride", coefficient: 2 },
      { name: "Water (Liquid)", coefficient: 1 },
      { name: "Carbon Dioxide", coefficient: 1 },
    ],
  },
  {
    name: "Permanganate Decomposition",
    equation: "2KMnO4 → K2MnO4 + MnO2 + O2↑",
    deltaH: 145,
    reactionType: "decomposition",
    isReversible: false,
    conditions: { temperature: 200 },
    description: "Endothermic decomposition of purple permanganate.",
    reactants: [{ name: "Potassium Permanganate", coefficient: 2 }],
    products: [
      { name: "Potassium Manganate", coefficient: 1 },
      { name: "Manganese Dioxide", coefficient: 1 },
      { name: "Oxygen", coefficient: 1 },
    ],
  },
  {
    name: "Cobalt Hydration",
    equation: "CoCl2·6H2O ⇌ CoCl2 + 6H2O",
    deltaH: 50,
    reactionType: "decomposition",
    isReversible: true,
    conditions: { temperature: 120 },
    description: "Pink → blue color change on heating, reversible.",
    reactants: [{ name: "Cobalt Chloride", coefficient: 1 }],
    products: [
      { name: "Cobalt Chloride", coefficient: 1 },
      { name: "Water (Liquid)", coefficient: 6 },
    ],
  },
];

async function main() {
  console.log("🌱 Seeding database...");

  // Clean existing data
  await db.reactionReactant.deleteMany();
  await db.reactionProduct.deleteMany();
  await db.reaction.deleteMany();
  await db.chemical.deleteMany();
  await db.labContainerState.deleteMany();
  await db.labState.deleteMany();
  console.log("  ✓ Cleared existing data");

  // Insert chemicals
  const chemIdMap = new Map<string, string>();
  for (const chem of chemicals) {
    const created = await db.chemical.create({
      data: {
        name: chem.name,
        formula: chem.formula,
        molarMass: chem.molarMass,
        density: chem.density,
        specificHeatCapacity: chem.specificHeatCapacity,
        surfaceTension: chem.surfaceTension,
        vaporPressure: chem.vaporPressure,
        boilingPoint: chem.boilingPoint,
        meltingPoint: chem.meltingPoint,
        hexColor: chem.hexColor,
        stateAtSTP: chem.stateAtSTP,
        hazards: JSON.stringify(chem.hazards),
        solubility: JSON.stringify(chem.solubility),
        refractiveIndex: chem.refractiveIndex,
        viscosity: chem.viscosity,
        category: chem.category,
        description: chem.description,
      },
    });
    chemIdMap.set(chem.name, created.id);
  }
  console.log(`  ✓ Inserted ${chemicals.length} chemicals`);

  // Insert reactions
  for (const rxn of reactions) {
    const created = await db.reaction.create({
      data: {
        name: rxn.name,
        equation: rxn.equation,
        deltaH: rxn.deltaH,
        reactionType: rxn.reactionType,
        isReversible: rxn.isReversible,
        conditions: JSON.stringify(rxn.conditions),
        description: rxn.description,
      },
    });
    for (const r of rxn.reactants) {
      const cid = chemIdMap.get(r.name);
      if (!cid) {
        console.warn(`  ⚠ Reactant chemical not found: ${r.name}`);
        continue;
      }
      await db.reactionReactant.create({
        data: {
          reactionId: created.id,
          chemicalId: cid,
          coefficient: r.coefficient,
          isLimiting: r.isLimiting || false,
        },
      });
    }
    for (const p of rxn.products) {
      const cid = chemIdMap.get(p.name);
      if (!cid) {
        console.warn(`  ⚠ Product chemical not found: ${p.name}`);
        continue;
      }
      await db.reactionProduct.create({
        data: {
          reactionId: created.id,
          chemicalId: cid,
          coefficient: p.coefficient,
        },
      });
    }
  }
  console.log(`  ✓ Inserted ${reactions.length} reactions`);

  // Create default lab state with 3 beakers
  const labState = await db.labState.create({
    data: { name: "default", isActive: true },
  });
  await db.labContainerState.createMany({
    data: [
      {
        labStateId: labState.id,
        containerId: "beaker-1",
        type: "beaker",
        positionX: -1.8,
        positionY: 0,
        positionZ: 0,
        capacity: 250,
      },
      {
        labStateId: labState.id,
        containerId: "beaker-2",
        type: "beaker",
        positionX: 0,
        positionY: 0,
        positionZ: 0,
        capacity: 400,
      },
      {
        labStateId: labState.id,
        containerId: "beaker-3",
        type: "beaker",
        positionX: 1.8,
        positionY: 0,
        positionZ: 0,
        capacity: 250,
      },
    ],
  });
  console.log("  ✓ Created default lab state with 3 beakers");

  console.log("\n✅ Seed complete!");
  console.log(`   ${chemicals.length} chemicals`);
  console.log(`   ${reactions.length} reactions`);
  console.log("   3 default beakers");
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
