import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const ELEMENTS = [
  { id: 'E001', iupacName: 'Hydrogen', formula: 'H', casNumber: '1333-74-0', hexColor: '#E8E8E8', opacity: 5, surfaceLuster: 'Matte', stateAt25C: 'Gas', density: 0.0000899, viscosity: 0.008, meltingPoint: -259.16, boilingPoint: -252.87, ghsHazards: 'GHS02-GHS04', smellDescription: 'Odourless', riskRating: 2, molarMass: 1.008, category: 'Element', specificHeatCapacity: 14.304, surfaceTension: 0.0, vaporPressure: 0.0 },
  { id: 'E002', iupacName: 'Helium', formula: 'He', casNumber: '7440-59-7', hexColor: '#D4F1F9', opacity: 5, surfaceLuster: 'Matte', stateAt25C: 'Gas', density: 0.0001785, viscosity: 0.008, meltingPoint: -272.2, boilingPoint: -268.93, ghsHazards: '', smellDescription: 'Odourless', riskRating: 1, molarMass: 4.003, category: 'Element', specificHeatCapacity: 5.193, surfaceTension: 0.0, vaporPressure: 0.0 },
  { id: 'E003', iupacName: 'Lithium', formula: 'Li', casNumber: '7439-93-2', hexColor: '#C4C4C4', opacity: 100, surfaceLuster: 'Metallic', stateAt25C: 'Solid', density: 0.534, viscosity: 0.6, meltingPoint: 180.54, boilingPoint: 1342, ghsHazards: 'GHS02-GHS05', smellDescription: 'Odourless', riskRating: 7, molarMass: 6.941, category: 'Element', specificHeatCapacity: 3.582, surfaceTension: 0.399, vaporPressure: 0.0 },
  { id: 'E004', iupacName: 'Beryllium', formula: 'Be', casNumber: '7440-41-7', hexColor: '#A8B5B0', opacity: 100, surfaceLuster: 'Metallic', stateAt25C: 'Solid', density: 1.85, viscosity: 0, meltingPoint: 1287, boilingPoint: 2470, ghsHazards: 'GHS06-GHS08', smellDescription: 'Odourless', riskRating: 8, molarMass: 9.012, category: 'Element', specificHeatCapacity: 1.825, surfaceTension: 1.1, vaporPressure: 0.0 },
  { id: 'E005', iupacName: 'Boron', formula: 'B', casNumber: '7440-42-8', hexColor: '#B5B5A8', opacity: 100, surfaceLuster: 'Matte', stateAt25C: 'Solid', density: 2.34, viscosity: 0, meltingPoint: 2076, boilingPoint: 3927, ghsHazards: '', smellDescription: 'Odourless', riskRating: 3, molarMass: 10.81, category: 'Element', specificHeatCapacity: 1.026, surfaceTension: 0.0, vaporPressure: 0.0 },
  { id: 'E006', iupacName: 'Carbon', formula: 'C', casNumber: '7440-44-0', hexColor: '#2C2C2C', opacity: 100, surfaceLuster: 'Matte', stateAt25C: 'Solid', density: 2.267, viscosity: 0, meltingPoint: 3550, boilingPoint: 4027, ghsHazards: '', smellDescription: 'Odourless', riskRating: 2, molarMass: 12.011, category: 'Element', specificHeatCapacity: 0.709, surfaceTension: 0.0, vaporPressure: 0.0 },
  { id: 'E007', iupacName: 'Nitrogen', formula: 'N', casNumber: '7727-37-9', hexColor: '#B0D4F1', opacity: 5, surfaceLuster: 'Matte', stateAt25C: 'Gas', density: 0.0012506, viscosity: 0.017, meltingPoint: -210.1, boilingPoint: -195.79, ghsHazards: '', smellDescription: 'Odourless', riskRating: 1, molarMass: 14.007, category: 'Element', specificHeatCapacity: 1.04, surfaceTension: 0.0, vaporPressure: 0.0 },
  { id: 'E008', iupacName: 'Oxygen', formula: 'O', casNumber: '7782-44-7', hexColor: '#9FC5E8', opacity: 5, surfaceLuster: 'Matte', stateAt25C: 'Gas', density: 0.001429, viscosity: 0.02, meltingPoint: -218.79, boilingPoint: -182.96, ghsHazards: 'GHS03', smellDescription: 'Odourless', riskRating: 2, molarMass: 15.999, category: 'Element', specificHeatCapacity: 0.918, surfaceTension: 0.0, vaporPressure: 0.0 },
  { id: 'E009', iupacName: 'Fluorine', formula: 'F', casNumber: '7782-41-4', hexColor: '#B6D7A8', opacity: 5, surfaceLuster: 'Matte', stateAt25C: 'Gas', density: 0.001696, viscosity: 0.023, meltingPoint: -219.67, boilingPoint: -188.12, ghsHazards: 'GHS04-GHS05-GHS06', smellDescription: 'Pungent', riskRating: 9, molarMass: 18.998, category: 'Element', specificHeatCapacity: 0.824, surfaceTension: 0.0, vaporPressure: 0.0 },
  { id: 'E010', iupacName: 'Neon', formula: 'Ne', casNumber: '7440-01-9', hexColor: '#FF6D6D', opacity: 5, surfaceLuster: 'Glassy', stateAt25C: 'Gas', density: 0.0008999, viscosity: 0.003, meltingPoint: -248.59, boilingPoint: -246.08, ghsHazards: '', smellDescription: 'Odourless', riskRating: 1, molarMass: 20.18, category: 'Element', specificHeatCapacity: 1.03, surfaceTension: 0.0, vaporPressure: 0.0 },
  { id: 'E011', iupacName: 'Sodium', formula: 'Na', casNumber: '7440-23-5', hexColor: '#C0A060', opacity: 100, surfaceLuster: 'Metallic', stateAt25C: 'Solid', density: 0.971, viscosity: 0.7, meltingPoint: 97.79, boilingPoint: 883, ghsHazards: 'GHS02-GHS05', smellDescription: 'Odourless', riskRating: 7, molarMass: 22.99, category: 'Element', specificHeatCapacity: 1.228, surfaceTension: 0.191, vaporPressure: 0.0 },
  { id: 'E012', iupacName: 'Magnesium', formula: 'Mg', casNumber: '7439-95-4', hexColor: '#D0D0D0', opacity: 100, surfaceLuster: 'Metallic', stateAt25C: 'Solid', density: 1.738, viscosity: 0, meltingPoint: 650, boilingPoint: 1091, ghsHazards: 'GHS02-GHS09', smellDescription: 'Odourless', riskRating: 5, molarMass: 24.305, category: 'Element', specificHeatCapacity: 1.023, surfaceTension: 0.565, vaporPressure: 0.0 },
  { id: 'E013', iupacName: 'Aluminium', formula: 'Al', casNumber: '7429-90-5', hexColor: '#C8C8C8', opacity: 100, surfaceLuster: 'Metallic', stateAt25C: 'Solid', density: 2.698, viscosity: 0, meltingPoint: 660.32, boilingPoint: 2519, ghsHazards: '', smellDescription: 'Odourless', riskRating: 3, molarMass: 26.982, category: 'Element', specificHeatCapacity: 0.897, surfaceTension: 0.868, vaporPressure: 0.0 },
  { id: 'E014', iupacName: 'Silicon', formula: 'Si', casNumber: '7440-21-3', hexColor: '#8C8C78', opacity: 100, surfaceLuster: 'Metallic', stateAt25C: 'Solid', density: 2.3296, viscosity: 0, meltingPoint: 1414, boilingPoint: 3265, ghsHazards: '', smellDescription: 'Odourless', riskRating: 2, molarMass: 28.086, category: 'Element', specificHeatCapacity: 0.71, surfaceTension: 0.0, vaporPressure: 0.0 },
  { id: 'E015', iupacName: 'Phosphorus (White)', formula: 'P', casNumber: '7723-14-0', hexColor: '#FFFFC0', opacity: 100, surfaceLuster: 'Waxy', stateAt25C: 'Solid', density: 1.823, viscosity: 0, meltingPoint: 44.15, boilingPoint: 280.5, ghsHazards: 'GHS02-GHS05-GHS06', smellDescription: 'Garlic-like', riskRating: 8, molarMass: 30.974, category: 'Element', specificHeatCapacity: 0.769, surfaceTension: 0.069, vaporPressure: 0.0 },
  { id: 'E016', iupacName: 'Sulfur', formula: 'S', casNumber: '7704-34-9', hexColor: '#E8D44D', opacity: 100, surfaceLuster: 'Matte', stateAt25C: 'Solid', density: 2.067, viscosity: 0, meltingPoint: 115.21, boilingPoint: 444.72, ghsHazards: '', smellDescription: 'Rotten eggs when burning', riskRating: 4, molarMass: 32.06, category: 'Element', specificHeatCapacity: 0.71, surfaceTension: 0.061, vaporPressure: 0.0 },
  { id: 'E017', iupacName: 'Chlorine', formula: 'Cl', casNumber: '7782-50-5', hexColor: '#C8F075', opacity: 5, surfaceLuster: 'Matte', stateAt25C: 'Gas', density: 0.003214, viscosity: 0.013, meltingPoint: -101.5, boilingPoint: -34.04, ghsHazards: 'GHS03-GHS05-GHS06', smellDescription: 'Pungent, suffocating', riskRating: 9, molarMass: 35.45, category: 'Element', specificHeatCapacity: 0.479, surfaceTension: 0.0, vaporPressure: 0.0 },
  { id: 'E018', iupacName: 'Argon', formula: 'Ar', casNumber: '7440-37-1', hexColor: '#A0C8E8', opacity: 5, surfaceLuster: 'Matte', stateAt25C: 'Gas', density: 0.0017837, viscosity: 0.022, meltingPoint: -189.34, boilingPoint: -185.85, ghsHazards: '', smellDescription: 'Odourless', riskRating: 1, molarMass: 39.948, category: 'Element', specificHeatCapacity: 0.52, surfaceTension: 0.0, vaporPressure: 0.0 },
  { id: 'E019', iupacName: 'Potassium', formula: 'K', casNumber: '7440-09-7', hexColor: '#C8B078', opacity: 100, surfaceLuster: 'Metallic', stateAt25C: 'Solid', density: 0.862, viscosity: 0.5, meltingPoint: 63.5, boilingPoint: 759, ghsHazards: 'GHS02-GHS05', smellDescription: 'Odourless', riskRating: 8, molarMass: 39.098, category: 'Element', specificHeatCapacity: 0.757, surfaceTension: 0.115, vaporPressure: 0.0 },
  { id: 'E020', iupacName: 'Calcium', formula: 'Ca', casNumber: '7440-70-2', hexColor: '#D0C8A8', opacity: 100, surfaceLuster: 'Metallic', stateAt25C: 'Solid', density: 1.55, viscosity: 0, meltingPoint: 842, boilingPoint: 1484, ghsHazards: '', smellDescription: 'Odourless', riskRating: 6, molarMass: 40.078, category: 'Element', specificHeatCapacity: 0.647, surfaceTension: 0.0, vaporPressure: 0.0 },
  { id: 'E021', iupacName: 'Scandium', formula: 'Sc', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 2.985, meltingPoint: 1541, boilingPoint: 2836, molarMass: 44.956, category: 'Element', riskRating: 3 },
  { id: 'E022', iupacName: 'Titanium', formula: 'Ti', hexColor: '#B8B8C0', stateAt25C: 'Solid', density: 4.506, meltingPoint: 1668, boilingPoint: 3287, molarMass: 47.867, category: 'Element', riskRating: 2 },
  { id: 'E023', iupacName: 'Vanadium', formula: 'V', hexColor: '#A0A0A8', stateAt25C: 'Solid', density: 6.11, meltingPoint: 1910, boilingPoint: 3407, molarMass: 50.942, category: 'Element', riskRating: 5 },
  { id: 'E024', iupacName: 'Chromium', formula: 'Cr', hexColor: '#C0B8A0', stateAt25C: 'Solid', density: 7.15, meltingPoint: 1907, boilingPoint: 2671, molarMass: 51.996, category: 'Element', riskRating: 6 },
  { id: 'E025', iupacName: 'Manganese', formula: 'Mn', hexColor: '#B0A898', stateAt25C: 'Solid', density: 7.44, meltingPoint: 1246, boilingPoint: 2061, molarMass: 54.938, category: 'Element', riskRating: 5 },
  { id: 'E026', iupacName: 'Iron', formula: 'Fe', casNumber: '7439-89-6', hexColor: '#8C8C8C', opacity: 100, surfaceLuster: 'Metallic', stateAt25C: 'Solid', density: 7.874, viscosity: 0, meltingPoint: 1538, boilingPoint: 2862, ghsHazards: '', smellDescription: 'Odourless', riskRating: 3, molarMass: 55.845, category: 'Element', specificHeatCapacity: 0.449, surfaceTension: 1.789, vaporPressure: 0.0 },
  { id: 'E027', iupacName: 'Cobalt', formula: 'Co', hexColor: '#4040C0', stateAt25C: 'Solid', density: 8.86, meltingPoint: 1495, boilingPoint: 2927, molarMass: 58.933, category: 'Element', riskRating: 6 },
  { id: 'E028', iupacName: 'Nickel', formula: 'Ni', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 8.912, meltingPoint: 1455, boilingPoint: 2913, molarMass: 58.693, category: 'Element', riskRating: 6 },
  { id: 'E029', iupacName: 'Copper', formula: 'Cu', casNumber: '7440-50-8', hexColor: '#B87333', opacity: 100, surfaceLuster: 'Metallic', stateAt25C: 'Solid', density: 8.96, viscosity: 0, meltingPoint: 1084.62, boilingPoint: 2562, ghsHazards: '', smellDescription: 'Odourless', riskRating: 4, molarMass: 63.546, category: 'Element', specificHeatCapacity: 0.385, surfaceTension: 1.303, vaporPressure: 0.0 },
  { id: 'E030', iupacName: 'Zinc', formula: 'Zn', hexColor: '#B0B0C0', stateAt25C: 'Solid', density: 7.134, meltingPoint: 419.53, boilingPoint: 907, molarMass: 65.38, category: 'Element', riskRating: 3 },
  { id: 'E031', iupacName: 'Gallium', formula: 'Ga', hexColor: '#C8C8D0', stateAt25C: 'Solid', density: 5.907, meltingPoint: 29.76, boilingPoint: 2204, molarMass: 69.723, category: 'Element', riskRating: 2 },
  { id: 'E032', iupacName: 'Germanium', formula: 'Ge', hexColor: '#B0B0B0', stateAt25C: 'Solid', density: 5.323, meltingPoint: 938.25, boilingPoint: 2833, molarMass: 72.63, category: 'Element', riskRating: 2 },
  { id: 'E033', iupacName: 'Arsenic', formula: 'As', hexColor: '#808060', stateAt25C: 'Solid', density: 5.727, meltingPoint: 817, boilingPoint: 614, molarMass: 74.922, category: 'Element', riskRating: 9 },
  { id: 'E034', iupacName: 'Selenium', formula: 'Se', hexColor: '#C0C070', stateAt25C: 'Solid', density: 4.809, meltingPoint: 221, boilingPoint: 685, molarMass: 78.971, category: 'Element', riskRating: 7 },
  { id: 'E035', iupacName: 'Bromine', formula: 'Br', hexColor: '#A0292E', opacity: 100, surfaceLuster: 'Glassy', stateAt25C: 'Liquid', density: 3.122, viscosity: 0.31, meltingPoint: -7.2, boilingPoint: 58.8, ghsHazards: 'GHS05-GHS06-GHS09', smellDescription: 'Choking, irritating', riskRating: 9, molarMass: 79.904, category: 'Element', specificHeatCapacity: 0.474, surfaceTension: 0.041, vaporPressure: 28.0 },
  { id: 'E036', iupacName: 'Krypton', formula: 'Kr', hexColor: '#A8D8F0', stateAt25C: 'Gas', density: 0.003749, meltingPoint: -157.36, boilingPoint: -153.22, molarMass: 83.798, category: 'Element', riskRating: 1 },
  { id: 'E037', iupacName: 'Rubidium', formula: 'Rb', hexColor: '#C8B898', stateAt25C: 'Solid', density: 1.532, meltingPoint: 39.31, boilingPoint: 688, molarMass: 85.468, category: 'Element', riskRating: 8 },
  { id: 'E038', iupacName: 'Strontium', formula: 'Sr', hexColor: '#D0C8B0', stateAt25C: 'Solid', density: 2.64, meltingPoint: 777, boilingPoint: 1382, molarMass: 87.62, category: 'Element', riskRating: 6 },
  { id: 'E039', iupacName: 'Yttrium', formula: 'Y', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 4.469, meltingPoint: 1526, boilingPoint: 3345, molarMass: 88.906, category: 'Element', riskRating: 3 },
  { id: 'E040', iupacName: 'Zirconium', formula: 'Zr', hexColor: '#B8B8B8', stateAt25C: 'Solid', density: 6.506, meltingPoint: 1855, boilingPoint: 4409, molarMass: 91.224, category: 'Element', riskRating: 3 },
  { id: 'E041', iupacName: 'Niobium', formula: 'Nb', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 8.57, meltingPoint: 2477, boilingPoint: 4744, molarMass: 92.906, category: 'Element', riskRating: 2 },
  { id: 'E042', iupacName: 'Molybdenum', formula: 'Mo', hexColor: '#B0B0B0', stateAt25C: 'Solid', density: 10.22, meltingPoint: 2623, boilingPoint: 4639, molarMass: 95.95, category: 'Element', riskRating: 3 },
  { id: 'E043', iupacName: 'Technetium', formula: 'Tc', hexColor: '#A0A0A0', stateAt25C: 'Solid', density: 11.5, meltingPoint: 2157, boilingPoint: 4265, molarMass: 98, category: 'Element', riskRating: 10 },
  { id: 'E044', iupacName: 'Ruthenium', formula: 'Ru', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 12.37, meltingPoint: 2334, boilingPoint: 4150, molarMass: 101.07, category: 'Element', riskRating: 3 },
  { id: 'E045', iupacName: 'Rhodium', formula: 'Rh', hexColor: '#E0E0E0', stateAt25C: 'Solid', density: 12.41, meltingPoint: 1964, boilingPoint: 3695, molarMass: 102.906, category: 'Element', riskRating: 2 },
  { id: 'E046', iupacName: 'Palladium', formula: 'Pd', hexColor: '#D0D0D0', stateAt25C: 'Solid', density: 12.02, meltingPoint: 1554.9, boilingPoint: 2963, molarMass: 106.42, category: 'Element', riskRating: 2 },
  { id: 'E047', iupacName: 'Silver', formula: 'Ag', casNumber: '7440-22-4', hexColor: '#E0E0E0', opacity: 100, surfaceLuster: 'Metallic', stateAt25C: 'Solid', density: 10.501, meltingPoint: 961.78, boilingPoint: 2162, molarMass: 107.868, category: 'Element', riskRating: 2, specificHeatCapacity: 0.235, surfaceTension: 0.925, vaporPressure: 0.0 },
  { id: 'E048', iupacName: 'Cadmium', formula: 'Cd', hexColor: '#D0D0C0', stateAt25C: 'Solid', density: 8.69, meltingPoint: 321.07, boilingPoint: 767, molarMass: 112.414, category: 'Element', riskRating: 9 },
  { id: 'E049', iupacName: 'Indium', formula: 'In', hexColor: '#D0D0E0', stateAt25C: 'Solid', density: 7.31, meltingPoint: 156.6, boilingPoint: 2072, molarMass: 114.818, category: 'Element', riskRating: 3 },
  { id: 'E050', iupacName: 'Tin', formula: 'Sn', hexColor: '#D0D0D0', stateAt25C: 'Solid', density: 7.287, meltingPoint: 231.93, boilingPoint: 2602, molarMass: 118.71, category: 'Element', riskRating: 3 },
  { id: 'E051', iupacName: 'Antimony', formula: 'Sb', hexColor: '#C8C8C8', stateAt25C: 'Solid', density: 6.685, meltingPoint: 630.63, boilingPoint: 1587, molarMass: 121.76, category: 'Element', riskRating: 6 },
  { id: 'E052', iupacName: 'Tellurium', formula: 'Te', hexColor: '#C0C0A0', stateAt25C: 'Solid', density: 6.232, meltingPoint: 449.51, boilingPoint: 988, molarMass: 127.6, category: 'Element', riskRating: 7 },
  { id: 'E053', iupacName: 'Iodine', formula: 'I', hexColor: '#4B0082', opacity: 100, surfaceLuster: 'Glassy', stateAt25C: 'Solid', density: 4.933, meltingPoint: 113.7, boilingPoint: 184.3, molarMass: 126.904, category: 'Element', riskRating: 6, specificHeatCapacity: 0.214 },
  { id: 'E054', iupacName: 'Xenon', formula: 'Xe', hexColor: '#A0D0F0', stateAt25C: 'Gas', density: 0.005887, meltingPoint: -111.75, boilingPoint: -108.09, molarMass: 131.293, category: 'Element', riskRating: 1 },
  { id: 'E055', iupacName: 'Cesium', formula: 'Cs', hexColor: '#C8B888', stateAt25C: 'Solid', density: 1.873, meltingPoint: 28.44, boilingPoint: 671, molarMass: 132.905, category: 'Element', riskRating: 9 },
  { id: 'E056', iupacName: 'Barium', formula: 'Ba', hexColor: '#D0C8A0', stateAt25C: 'Solid', density: 3.594, meltingPoint: 727, boilingPoint: 1845, molarMass: 137.327, category: 'Element', riskRating: 7 },
  { id: 'E057', iupacName: 'Lanthanum', formula: 'La', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 6.145, meltingPoint: 920, boilingPoint: 3464, molarMass: 138.905, category: 'Element', riskRating: 3 },
  { id: 'E058', iupacName: 'Cerium', formula: 'Ce', hexColor: '#D0C8C0', stateAt25C: 'Solid', density: 6.77, meltingPoint: 799, boilingPoint: 3443, molarMass: 140.116, category: 'Element', riskRating: 3 },
  { id: 'E059', iupacName: 'Praseodymium', formula: 'Pr', hexColor: '#C8C0B8', stateAt25C: 'Solid', density: 6.773, meltingPoint: 931, boilingPoint: 3520, molarMass: 140.908, category: 'Element', riskRating: 3 },
  { id: 'E060', iupacName: 'Neodymium', formula: 'Nd', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 7.007, meltingPoint: 1021, boilingPoint: 3074, molarMass: 144.242, category: 'Element', riskRating: 3 },
  { id: 'E061', iupacName: 'Promethium', formula: 'Pm', hexColor: '#C0B8B0', stateAt25C: 'Solid', density: 7.26, meltingPoint: 1042, boilingPoint: 3000, molarMass: 145, category: 'Element', riskRating: 10 },
  { id: 'E062', iupacName: 'Samarium', formula: 'Sm', hexColor: '#C8C0C0', stateAt25C: 'Solid', density: 7.52, meltingPoint: 1074, boilingPoint: 1794, molarMass: 150.36, category: 'Element', riskRating: 3 },
  { id: 'E063', iupacName: 'Europium', formula: 'Eu', hexColor: '#D0D0D0', stateAt25C: 'Solid', density: 5.243, meltingPoint: 822, boilingPoint: 1529, molarMass: 151.964, category: 'Element', riskRating: 3 },
  { id: 'E064', iupacName: 'Gadolinium', formula: 'Gd', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 7.895, meltingPoint: 1313, boilingPoint: 3273, molarMass: 157.25, category: 'Element', riskRating: 3 },
  { id: 'E065', iupacName: 'Terbium', formula: 'Tb', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 8.229, meltingPoint: 1356, boilingPoint: 3230, molarMass: 158.925, category: 'Element', riskRating: 3 },
  { id: 'E066', iupacName: 'Dysprosium', formula: 'Dy', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 8.55, meltingPoint: 1412, boilingPoint: 2567, molarMass: 162.5, category: 'Element', riskRating: 3 },
  { id: 'E067', iupacName: 'Holmium', formula: 'Ho', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 8.795, meltingPoint: 1474, boilingPoint: 2700, molarMass: 164.93, category: 'Element', riskRating: 3 },
  { id: 'E068', iupacName: 'Erbium', formula: 'Er', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 9.066, meltingPoint: 1529, boilingPoint: 2868, molarMass: 167.259, category: 'Element', riskRating: 3 },
  { id: 'E069', iupacName: 'Thulium', formula: 'Tm', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 9.321, meltingPoint: 1545, boilingPoint: 1950, molarMass: 168.934, category: 'Element', riskRating: 3 },
  { id: 'E070', iupacName: 'Ytterbium', formula: 'Yb', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 6.965, meltingPoint: 819, boilingPoint: 1196, molarMass: 173.054, category: 'Element', riskRating: 3 },
  { id: 'E071', iupacName: 'Lutetium', formula: 'Lu', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 9.84, meltingPoint: 1663, boilingPoint: 3402, molarMass: 174.967, category: 'Element', riskRating: 3 },
  { id: 'E072', iupacName: 'Hafnium', formula: 'Hf', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 13.31, meltingPoint: 2233, boilingPoint: 4603, molarMass: 178.49, category: 'Element', riskRating: 3 },
  { id: 'E073', iupacName: 'Tantalum', formula: 'Ta', hexColor: '#C0C8D0', stateAt25C: 'Solid', density: 16.654, meltingPoint: 3017, boilingPoint: 5458, molarMass: 180.948, category: 'Element', riskRating: 2 },
  { id: 'E074', iupacName: 'Tungsten', formula: 'W', hexColor: '#B0B0B0', stateAt25C: 'Solid', density: 19.25, meltingPoint: 3422, boilingPoint: 5555, molarMass: 183.84, category: 'Element', riskRating: 2 },
  { id: 'E075', iupacName: 'Rhenium', formula: 'Re', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 21.02, meltingPoint: 3186, boilingPoint: 5596, molarMass: 186.207, category: 'Element', riskRating: 2 },
  { id: 'E076', iupacName: 'Osmium', formula: 'Os', hexColor: '#C0C0C8', stateAt25C: 'Solid', density: 22.59, meltingPoint: 3033, boilingPoint: 5012, molarMass: 190.23, category: 'Element', riskRating: 7 },
  { id: 'E077', iupacName: 'Iridium', formula: 'Ir', hexColor: '#E0E0E0', stateAt25C: 'Solid', density: 22.56, meltingPoint: 2446, boilingPoint: 4428, molarMass: 192.217, category: 'Element', riskRating: 2 },
  { id: 'E078', iupacName: 'Platinum', formula: 'Pt', hexColor: '#E0E0E0', stateAt25C: 'Solid', density: 21.46, meltingPoint: 1768.3, boilingPoint: 3825, molarMass: 195.084, category: 'Element', riskRating: 2 },
  { id: 'E079', iupacName: 'Gold', formula: 'Au', casNumber: '7440-57-5', hexColor: '#FFD700', opacity: 100, surfaceLuster: 'Metallic', stateAt25C: 'Solid', density: 19.282, meltingPoint: 1064.18, boilingPoint: 2856, molarMass: 196.967, category: 'Element', riskRating: 1, specificHeatCapacity: 0.129, surfaceTension: 1.14, vaporPressure: 0.0 },
  { id: 'E080', iupacName: 'Mercury', formula: 'Hg', casNumber: '7439-97-6', hexColor: '#C0C0C0', opacity: 100, surfaceLuster: 'Metallic', stateAt25C: 'Liquid', density: 13.5336, viscosity: 1.53, meltingPoint: -38.83, boilingPoint: 356.73, ghsHazards: 'GHS06-GHS08', smellDescription: 'Odourless', riskRating: 9, molarMass: 200.592, category: 'Element', specificHeatCapacity: 0.139, surfaceTension: 0.487, vaporPressure: 0.27 },
  { id: 'E081', iupacName: 'Thallium', formula: 'Tl', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 11.85, meltingPoint: 304, boilingPoint: 1473, molarMass: 204.38, category: 'Element', riskRating: 10 },
  { id: 'E082', iupacName: 'Lead', formula: 'Pb', casNumber: '7439-92-1', hexColor: '#505050', opacity: 100, surfaceLuster: 'Metallic', stateAt25C: 'Solid', density: 11.342, meltingPoint: 327.46, boilingPoint: 1749, ghsHazards: 'GHS07-GHS08', smellDescription: 'Odourless', riskRating: 7, molarMass: 207.2, category: 'Element', specificHeatCapacity: 0.129, surfaceTension: 0.45, vaporPressure: 0.0 },
  { id: 'E083', iupacName: 'Bismuth', formula: 'Bi', hexColor: '#E8C8C8', stateAt25C: 'Solid', density: 9.807, meltingPoint: 271.5, boilingPoint: 1564, molarMass: 208.98, category: 'Element', riskRating: 4 },
  { id: 'E084', iupacName: 'Polonium', formula: 'Po', hexColor: '#C0C0A0', stateAt25C: 'Solid', density: 9.32, meltingPoint: 254, boilingPoint: 962, molarMass: 209, category: 'Element', riskRating: 10 },
  { id: 'E085', iupacName: 'Astatine', formula: 'At', hexColor: '#2C0030', stateAt25C: 'Solid', density: 7, meltingPoint: 302, boilingPoint: 337, molarMass: 210, category: 'Element', riskRating: 10 },
  { id: 'E086', iupacName: 'Radon', formula: 'Rn', hexColor: '#A0A0D0', stateAt25C: 'Gas', density: 0.00973, meltingPoint: -71, boilingPoint: -61.7, molarMass: 222, category: 'Element', riskRating: 10 },
  { id: 'E087', iupacName: 'Francium', formula: 'Fr', hexColor: '#C0B898', stateAt25C: 'Solid', density: 2.48, meltingPoint: 27, boilingPoint: 677, molarMass: 223, category: 'Element', riskRating: 10 },
  { id: 'E088', iupacName: 'Radium', formula: 'Ra', hexColor: '#D0D0C0', stateAt25C: 'Solid', density: 5.5, meltingPoint: 700, boilingPoint: 1500, molarMass: 226, category: 'Element', riskRating: 10 },
  { id: 'E089', iupacName: 'Actinium', formula: 'Ac', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 10.07, meltingPoint: 1050, boilingPoint: 3198, molarMass: 227, category: 'Element', riskRating: 10 },
  { id: 'E090', iupacName: 'Thorium', formula: 'Th', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 11.72, meltingPoint: 1750, boilingPoint: 4788, molarMass: 232.038, category: 'Element', riskRating: 8 },
  { id: 'E091', iupacName: 'Protactinium', formula: 'Pa', hexColor: '#C0C0B0', stateAt25C: 'Solid', density: 15.37, meltingPoint: 1572, boilingPoint: 4027, molarMass: 231.036, category: 'Element', riskRating: 10 },
  { id: 'E092', iupacName: 'Uranium', formula: 'U', hexColor: '#909070', stateAt25C: 'Solid', density: 19.05, meltingPoint: 1135, boilingPoint: 4131, molarMass: 238.029, category: 'Element', riskRating: 10 },
  { id: 'E093', iupacName: 'Neptunium', formula: 'Np', hexColor: '#A0A0A0', stateAt25C: 'Solid', density: 20.45, meltingPoint: 644, boilingPoint: 3902, molarMass: 237, category: 'Element', riskRating: 10 },
  { id: 'E094', iupacName: 'Plutonium', formula: 'Pu', hexColor: '#A0A090', stateAt25C: 'Solid', density: 19.84, meltingPoint: 640, boilingPoint: 3228, molarMass: 244, category: 'Element', riskRating: 10 },
  { id: 'E095', iupacName: 'Americium', formula: 'Am', hexColor: '#B0B0A0', stateAt25C: 'Solid', density: 12, meltingPoint: 1176, boilingPoint: 2011, molarMass: 243, category: 'Element', riskRating: 10 },
  { id: 'E096', iupacName: 'Curium', formula: 'Cm', hexColor: '#B0B0B0', stateAt25C: 'Solid', density: 13.51, meltingPoint: 1345, boilingPoint: 3110, molarMass: 247, category: 'Element', riskRating: 10 },
  { id: 'E097', iupacName: 'Berkelium', formula: 'Bk', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 14.79, meltingPoint: 1050, boilingPoint: 2627, molarMass: 247, category: 'Element', riskRating: 10 },
  { id: 'E098', iupacName: 'Californium', formula: 'Cf', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 15.1, meltingPoint: 900, boilingPoint: 1472, molarMass: 251, category: 'Element', riskRating: 10 },
  { id: 'E099', iupacName: 'Einsteinium', formula: 'Es', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 8.84, meltingPoint: 860, boilingPoint: 996, molarMass: 252, category: 'Element', riskRating: 10 },
  { id: 'E100', iupacName: 'Fermium', formula: 'Fm', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 0, meltingPoint: 0, boilingPoint: 0, molarMass: 257, category: 'Element', riskRating: 10 },
  { id: 'E101', iupacName: 'Mendelevium', formula: 'Md', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 0, meltingPoint: 0, boilingPoint: 0, molarMass: 258, category: 'Element', riskRating: 10 },
  { id: 'E102', iupacName: 'Nobelium', formula: 'No', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 0, meltingPoint: 0, boilingPoint: 0, molarMass: 259, category: 'Element', riskRating: 10 },
  { id: 'E103', iupacName: 'Lawrencium', formula: 'Lr', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 0, meltingPoint: 0, boilingPoint: 0, molarMass: 266, category: 'Element', riskRating: 10 },
  { id: 'E104', iupacName: 'Rutherfordium', formula: 'Rf', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 0, meltingPoint: 0, boilingPoint: 0, molarMass: 267, category: 'Element', riskRating: 10 },
  { id: 'E105', iupacName: 'Dubnium', formula: 'Db', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 0, meltingPoint: 0, boilingPoint: 0, molarMass: 268, category: 'Element', riskRating: 10 },
  { id: 'E106', iupacName: 'Seaborgium', formula: 'Sg', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 0, meltingPoint: 0, boilingPoint: 0, molarMass: 269, category: 'Element', riskRating: 10 },
  { id: 'E107', iupacName: 'Bohrium', formula: 'Bh', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 0, meltingPoint: 0, boilingPoint: 0, molarMass: 270, category: 'Element', riskRating: 10 },
  { id: 'E108', iupacName: 'Hassium', formula: 'Hs', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 0, meltingPoint: 0, boilingPoint: 0, molarMass: 277, category: 'Element', riskRating: 10 },
  { id: 'E109', iupacName: 'Meitnerium', formula: 'Mt', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 0, meltingPoint: 0, boilingPoint: 0, molarMass: 278, category: 'Element', riskRating: 10 },
  { id: 'E110', iupacName: 'Darmstadtium', formula: 'Ds', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 0, meltingPoint: 0, boilingPoint: 0, molarMass: 281, category: 'Element', riskRating: 10 },
  { id: 'E111', iupacName: 'Roentgenium', formula: 'Rg', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 0, meltingPoint: 0, boilingPoint: 0, molarMass: 282, category: 'Element', riskRating: 10 },
  { id: 'E112', iupacName: 'Copernicium', formula: 'Cn', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 0, meltingPoint: 0, boilingPoint: 357, molarMass: 285, category: 'Element', riskRating: 10 },
  { id: 'E113', iupacName: 'Nihonium', formula: 'Nh', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 0, meltingPoint: 0, boilingPoint: 0, molarMass: 286, category: 'Element', riskRating: 10 },
  { id: 'E114', iupacName: 'Flerovium', formula: 'Fl', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 0, meltingPoint: 0, boilingPoint: 210, molarMass: 289, category: 'Element', riskRating: 10 },
  { id: 'E115', iupacName: 'Moscovium', formula: 'Mc', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 0, meltingPoint: 0, boilingPoint: 0, molarMass: 290, category: 'Element', riskRating: 10 },
  { id: 'E116', iupacName: 'Livermorium', formula: 'Lv', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 0, meltingPoint: 0, boilingPoint: 0, molarMass: 293, category: 'Element', riskRating: 10 },
  { id: 'E117', iupacName: 'Tennessine', formula: 'Ts', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 0, meltingPoint: 0, boilingPoint: 0, molarMass: 294, category: 'Element', riskRating: 10 },
  { id: 'E118', iupacName: 'Oganesson', formula: 'Og', hexColor: '#C0C0C0', stateAt25C: 'Solid', density: 0, meltingPoint: 0, boilingPoint: 0, molarMass: 294, category: 'Element', riskRating: 10 },
];

const COMPOUNDS = [
  { id: 'C001', iupacName: 'Water', formula: 'H2O', casNumber: '7732-18-5', hexColor: '#E8F4FD', opacity: 40, surfaceLuster: 'Glassy', stateAt25C: 'Liquid', density: 0.997, viscosity: 1.002, meltingPoint: 0, boilingPoint: 100, ghsHazards: '', smellDescription: 'Odourless', riskRating: 1, molarMass: 18.015, category: 'Solvent', specificHeatCapacity: 4.18, surfaceTension: 0.0728, vaporPressure: 3.17 },
  { id: 'C002', iupacName: 'Sodium Chloride', formula: 'NaCl', casNumber: '7647-14-5', hexColor: '#FFFFFF', opacity: 100, surfaceLuster: 'Glassy', stateAt25C: 'Solid', density: 2.165, viscosity: 0, meltingPoint: 800.7, boilingPoint: 1413, ghsHazards: '', smellDescription: 'Odourless', riskRating: 1, molarMass: 58.44, category: 'Salt', specificHeatCapacity: 0.854, surfaceTension: 0.0, vaporPressure: 0.0 },
  { id: 'C003', iupacName: 'Hydrochloric Acid (37%)', formula: 'HCl', casNumber: '7647-01-0', hexColor: '#D0E8F0', opacity: 60, surfaceLuster: 'Glassy', stateAt25C: 'Liquid', density: 1.19, viscosity: 1.6, meltingPoint: -114.22, boilingPoint: -85.05, ghsHazards: 'GHS05-GHS07', smellDescription: 'Pungent, irritating', riskRating: 7, molarMass: 36.461, category: 'Acid', specificHeatCapacity: 3.14, surfaceTension: 0.065, vaporPressure: 42.7 },
  { id: 'C004', iupacName: 'Sulfuric Acid (98%)', formula: 'H2SO4', casNumber: '7664-93-9', hexColor: '#D0E0F0', opacity: 70, surfaceLuster: 'Glassy', stateAt25C: 'Liquid', density: 1.84, viscosity: 24.5, meltingPoint: 10, boilingPoint: 337, ghsHazards: 'GHS05', smellDescription: 'Odourless', riskRating: 8, molarMass: 98.079, category: 'Acid', specificHeatCapacity: 1.38, surfaceTension: 0.055, vaporPressure: 0.001 },
  { id: 'C005', iupacName: 'Nitric Acid (70%)', formula: 'HNO3', casNumber: '7697-37-2', hexColor: '#D8F0D8', opacity: 60, surfaceLuster: 'Glassy', stateAt25C: 'Liquid', density: 1.42, viscosity: 0.8, meltingPoint: -41.6, boilingPoint: 83, ghsHazards: 'GHS03-GHS05', smellDescription: 'Acrid, suffocating', riskRating: 8, molarMass: 63.012, category: 'Acid', specificHeatCapacity: 1.73, surfaceTension: 0.053, vaporPressure: 6.4 },
  { id: 'C006', iupacName: 'Acetic Acid (Glacial)', formula: 'CH3COOH', casNumber: '64-19-7', hexColor: '#F0F0D0', opacity: 70, surfaceLuster: 'Glassy', stateAt25C: 'Liquid', density: 1.049, viscosity: 1.16, meltingPoint: 16.6, boilingPoint: 118.1, ghsHazards: 'GHS02-GHS05', smellDescription: 'Vinegar-like', riskRating: 5, molarMass: 60.052, category: 'Acid', specificHeatCapacity: 2.04, surfaceTension: 0.027, vaporPressure: 2.1 },
  { id: 'C007', iupacName: 'Sodium Hydroxide', formula: 'NaOH', casNumber: '1310-73-2', hexColor: '#F0F0F0', opacity: 100, surfaceLuster: 'Matte', stateAt25C: 'Solid', density: 2.13, viscosity: 0, meltingPoint: 323, boilingPoint: 1388, ghsHazards: 'GHS05', smellDescription: 'Odourless', riskRating: 7, molarMass: 40.0, category: 'Base', specificHeatCapacity: 1.49, surfaceTension: 0.0, vaporPressure: 0.0 },
  { id: 'C008', iupacName: 'Ammonia (Aqueous 28%)', formula: 'NH3', casNumber: '7664-41-7', hexColor: '#E0F0F0', opacity: 50, surfaceLuster: 'Glassy', stateAt25C: 'Liquid', density: 0.9, viscosity: 0.2, meltingPoint: -77.73, boilingPoint: -33.34, ghsHazards: 'GHS02-GHS05-GHS06', smellDescription: 'Pungent, suffocating', riskRating: 7, molarMass: 17.031, category: 'Base', specificHeatCapacity: 4.7, surfaceTension: 0.023, vaporPressure: 9.9 },
  { id: 'C009', iupacName: 'Ethanol (Absolute)', formula: 'C2H5OH', casNumber: '64-17-5', hexColor: '#F0F8FF', opacity: 40, surfaceLuster: 'Glassy', stateAt25C: 'Liquid', density: 0.789, viscosity: 1.074, meltingPoint: -114.1, boilingPoint: 78.37, ghsHazards: 'GHS02', smellDescription: 'Sweet, alcoholic', riskRating: 3, molarMass: 46.069, category: 'Solvent', specificHeatCapacity: 2.44, surfaceTension: 0.022, vaporPressure: 7.9 },
  { id: 'C010', iupacName: 'Methanol', formula: 'CH3OH', casNumber: '67-56-1', hexColor: '#F0F8FF', opacity: 40, surfaceLuster: 'Glassy', stateAt25C: 'Liquid', density: 0.792, viscosity: 0.544, meltingPoint: -97.6, boilingPoint: 64.7, ghsHazards: 'GHS02-GHS06-GHS08', smellDescription: 'Sweet, alcoholic', riskRating: 6, molarMass: 32.042, category: 'Solvent', specificHeatCapacity: 2.53, surfaceTension: 0.023, vaporPressure: 16.9 },
  { id: 'C011', iupacName: 'Acetone', formula: '(CH3)2CO', casNumber: '67-64-1', hexColor: '#F0F8FF', opacity: 30, surfaceLuster: 'Glassy', stateAt25C: 'Liquid', density: 0.791, viscosity: 0.306, meltingPoint: -94.7, boilingPoint: 56.05, ghsHazards: 'GHS02-GHS07', smellDescription: 'Sweet, fruity', riskRating: 4, molarMass: 58.08, category: 'Solvent', specificHeatCapacity: 2.17, surfaceTension: 0.024, vaporPressure: 30.8 },
  { id: 'C012', iupacName: 'Hydrogen Peroxide (30%)', formula: 'H2O2', casNumber: '7722-84-1', hexColor: '#F0F0FF', opacity: 50, surfaceLuster: 'Glassy', stateAt25C: 'Liquid', density: 1.11, viscosity: 1.25, meltingPoint: -0.43, boilingPoint: 150.2, ghsHazards: 'GHS03-GHS05-GHS07', smellDescription: 'Slightly sharp', riskRating: 6, molarMass: 34.014, category: 'Oxidizer', specificHeatCapacity: 2.62, surfaceTension: 0.076, vaporPressure: 0.3 },
  { id: 'C013', iupacName: 'Copper(II) Sulfate Pentahydrate', formula: 'CuSO4·5H2O', casNumber: '7758-99-8', hexColor: '#1E90FF', opacity: 100, surfaceLuster: 'Glassy', stateAt25C: 'Solid', density: 2.284, viscosity: 0, meltingPoint: 150, boilingPoint: 650, ghsHazards: 'GHS07-GHS09', smellDescription: 'Odourless', riskRating: 5, molarMass: 249.685, category: 'Salt', specificHeatCapacity: 0.86, surfaceTension: 0.0, vaporPressure: 0.0 },
  { id: 'C014', iupacName: 'Iron(III) Chloride', formula: 'FeCl3', casNumber: '7705-08-0', hexColor: '#8B4513', opacity: 100, surfaceLuster: 'Matte', stateAt25C: 'Solid', density: 2.898, viscosity: 0, meltingPoint: 306, boilingPoint: 315, ghsHazards: 'GHS05-GHS07', smellDescription: 'Slight HCl odor', riskRating: 5, molarMass: 162.2, category: 'Salt', specificHeatCapacity: 0.66, surfaceTension: 0.0, vaporPressure: 0.0 },
  { id: 'C015', iupacName: 'Potassium Permanganate', formula: 'KMnO4', casNumber: '7722-64-7', hexColor: '#8B008B', opacity: 100, surfaceLuster: 'Glassy', stateAt25C: 'Solid', density: 2.703, viscosity: 0, meltingPoint: 240, boilingPoint: 535, ghsHazards: 'GHS03-GHS05-GHS07', smellDescription: 'Odourless', riskRating: 6, molarMass: 158.034, category: 'Oxidizer', specificHeatCapacity: 0.64, surfaceTension: 0.0, vaporPressure: 0.0 },
  { id: 'C016', iupacName: 'Sodium Carbonate', formula: 'Na2CO3', casNumber: '497-19-8', hexColor: '#FFFFFF', opacity: 100, surfaceLuster: 'Glassy', stateAt25C: 'Solid', density: 2.54, viscosity: 0, meltingPoint: 851, boilingPoint: 1600, ghsHazards: '', smellDescription: 'Odourless', riskRating: 2, molarMass: 105.989, category: 'Salt', specificHeatCapacity: 1.09, surfaceTension: 0.0, vaporPressure: 0.0 },
  { id: 'C017', iupacName: 'Calcium Carbonate', formula: 'CaCO3', casNumber: '471-34-1', hexColor: '#F5F5F0', opacity: 100, surfaceLuster: 'Matte', stateAt25C: 'Solid', density: 2.711, viscosity: 0, meltingPoint: 1339, boilingPoint: 898, ghsHazards: '', smellDescription: 'Odourless', riskRating: 1, molarMass: 100.087, category: 'Salt', specificHeatCapacity: 0.83, surfaceTension: 0.0, vaporPressure: 0.0 },
  { id: 'C018', iupacName: 'Sodium Bicarbonate', formula: 'NaHCO3', casNumber: '144-55-8', hexColor: '#FFFFFF', opacity: 100, surfaceLuster: 'Matte', stateAt25C: 'Solid', density: 2.2, viscosity: 0, meltingPoint: 50, boilingPoint: 0, ghsHazards: '', smellDescription: 'Odourless', riskRating: 1, molarMass: 84.007, category: 'Salt', specificHeatCapacity: 1.02, surfaceTension: 0.0, vaporPressure: 0.0 },
  { id: 'C019', iupacName: 'Potassium Iodide', formula: 'KI', casNumber: '7681-11-0', hexColor: '#F0F0F0', opacity: 100, surfaceLuster: 'Glassy', stateAt25C: 'Solid', density: 3.13, viscosity: 0, meltingPoint: 681, boilingPoint: 1330, ghsHazards: '', smellDescription: 'Odourless', riskRating: 2, molarMass: 166.003, category: 'Salt', specificHeatCapacity: 0.33, surfaceTension: 0.0, vaporPressure: 0.0 },
  { id: 'C020', iupacName: 'Silver Nitrate', formula: 'AgNO3', casNumber: '7761-88-8', hexColor: '#E8E8E8', opacity: 100, surfaceLuster: 'Glassy', stateAt25C: 'Solid', density: 4.352, viscosity: 0, meltingPoint: 209.7, boilingPoint: 444, ghsHazards: 'GHS03-GHS05-GHS09', smellDescription: 'Odourless', riskRating: 6, molarMass: 169.872, category: 'Salt', specificHeatCapacity: 0.33, surfaceTension: 0.0, vaporPressure: 0.0 },
  { id: 'C021', iupacName: 'Lead(II) Nitrate', formula: 'Pb(NO3)2', casNumber: '10099-74-8', hexColor: '#F0F0F0', opacity: 100, surfaceLuster: 'Glassy', stateAt25C: 'Solid', density: 4.53, viscosity: 0, meltingPoint: 270, boilingPoint: 0, ghsHazards: 'GHS03-GHS08-GHS09', smellDescription: 'Odourless', riskRating: 8, molarMass: 331.2, category: 'Salt', specificHeatCapacity: 0.33, surfaceTension: 0.0, vaporPressure: 0.0 },
  { id: 'C022', iupacName: 'Barium Chloride', formula: 'BaCl2', casNumber: '10361-37-2', hexColor: '#F0F0F0', opacity: 100, surfaceLuster: 'Glassy', stateAt25C: 'Solid', density: 3.856, viscosity: 0, meltingPoint: 962, boilingPoint: 1560, ghsHazards: 'GHS06', smellDescription: 'Odourless', riskRating: 7, molarMass: 208.23, category: 'Salt', specificHeatCapacity: 0.38, surfaceTension: 0.0, vaporPressure: 0.0 },
  { id: 'C023', iupacName: 'Calcium Chloride', formula: 'CaCl2', casNumber: '10043-52-4', hexColor: '#F0F0F0', opacity: 100, surfaceLuster: 'Glassy', stateAt25C: 'Solid', density: 2.15, viscosity: 0, meltingPoint: 772, boilingPoint: 1935, ghsHazards: '', smellDescription: 'Odourless', riskRating: 2, molarMass: 110.98, category: 'Salt', specificHeatCapacity: 0.64, surfaceTension: 0.0, vaporPressure: 0.0 },
  { id: 'C024', iupacName: 'Manganese Dioxide', formula: 'MnO2', casNumber: '1313-13-9', hexColor: '#2C2C2C', opacity: 100, surfaceLuster: 'Matte', stateAt25C: 'Solid', density: 5.026, viscosity: 0, meltingPoint: 535, boilingPoint: 0, ghsHazards: '', smellDescription: 'Odourless', riskRating: 4, molarMass: 86.937, category: 'Oxidizer', specificHeatCapacity: 0.55, surfaceTension: 0.0, vaporPressure: 0.0 },
  { id: 'C025', iupacName: 'Zinc Sulfate Heptahydrate', formula: 'ZnSO4·7H2O', casNumber: '7446-20-0', hexColor: '#F0F0F0', opacity: 100, surfaceLuster: 'Glassy', stateAt25C: 'Solid', density: 1.957, viscosity: 0, meltingPoint: 100, boilingPoint: 0, ghsHazards: 'GHS07-GHS09', smellDescription: 'Odourless', riskRating: 4, molarMass: 287.56, category: 'Salt', specificHeatCapacity: 0.83, surfaceTension: 0.0, vaporPressure: 0.0 },
  { id: 'C026', iupacName: 'Iron(II) Sulfate Heptahydrate', formula: 'FeSO4·7H2O', casNumber: '7782-63-0', hexColor: '#90EE90', opacity: 100, surfaceLuster: 'Glassy', stateAt25C: 'Solid', density: 1.898, viscosity: 0, meltingPoint: 70, boilingPoint: 330, ghsHazards: 'GHS07', smellDescription: 'Odourless', riskRating: 3, molarMass: 278.015, category: 'Salt', specificHeatCapacity: 0.72, surfaceTension: 0.0, vaporPressure: 0.0 },
  { id: 'C027', iupacName: 'Cobalt(II) Chloride Hexahydrate', formula: 'CoCl2·6H2O', casNumber: '7791-13-1', hexColor: '#FF1493', opacity: 100, surfaceLuster: 'Glassy', stateAt25C: 'Solid', density: 1.924, viscosity: 0, meltingPoint: 87, boilingPoint: 1049, ghsHazards: 'GHS07-GHS08', smellDescription: 'Odourless', riskRating: 5, molarMass: 237.93, category: 'Salt', specificHeatCapacity: 0.77, surfaceTension: 0.0, vaporPressure: 0.0 },
  { id: 'C028', iupacName: 'Aluminium Oxide', formula: 'Al2O3', casNumber: '1344-28-1', hexColor: '#F0F0F0', opacity: 100, surfaceLuster: 'Glassy', stateAt25C: 'Solid', density: 3.95, viscosity: 0, meltingPoint: 2072, boilingPoint: 2977, ghsHazards: '', smellDescription: 'Odourless', riskRating: 2, molarMass: 101.961, category: 'Salt', specificHeatCapacity: 0.88, surfaceTension: 0.0, vaporPressure: 0.0 },
  { id: 'C029', iupacName: 'Carbon Dioxide', formula: 'CO2', casNumber: '124-38-9', hexColor: '#F0F8FF', opacity: 5, surfaceLuster: 'Matte', stateAt25C: 'Gas', density: 0.001842, viscosity: 0.015, meltingPoint: -56.6, boilingPoint: -78.5, ghsHazards: '', smellDescription: 'Odourless', riskRating: 2, molarMass: 44.01, category: 'Gas', specificHeatCapacity: 0.844, surfaceTension: 0.0, vaporPressure: 5730.0 },
  { id: 'C030', iupacName: 'Sodium Thiosulfate', formula: 'Na2S2O3', casNumber: '7772-98-7', hexColor: '#F0F0F0', opacity: 100, surfaceLuster: 'Glassy', stateAt25C: 'Solid', density: 1.667, viscosity: 0, meltingPoint: 48, boilingPoint: 0, ghsHazards: '', smellDescription: 'Odourless', riskRating: 1, molarMass: 158.11, category: 'Salt', specificHeatCapacity: 0.65, surfaceTension: 0.0, vaporPressure: 0.0 },
  { id: 'C031', iupacName: 'Phenolphthalein', formula: 'C20H14O4', casNumber: '77-09-8', hexColor: '#F0E0F0', opacity: 100, surfaceLuster: 'Glassy', stateAt25C: 'Solid', density: 1.277, viscosity: 0, meltingPoint: 261, boilingPoint: 0, ghsHazards: '', smellDescription: 'Odourless', riskRating: 3, molarMass: 318.33, category: 'Indicator', specificHeatCapacity: 1.2, surfaceTension: 0.0, vaporPressure: 0.0 },
  { id: 'C032', iupacName: 'Litmus (in solution)', formula: 'Mixture', hexColor: '#6A0DAD', opacity: 60, surfaceLuster: 'Glassy', stateAt25C: 'Liquid', density: 1.01, viscosity: 1.0, meltingPoint: 0, boilingPoint: 100, ghsHazards: '', smellDescription: 'Odourless', riskRating: 1, molarMass: 40, category: 'Indicator', specificHeatCapacity: 4.18, surfaceTension: 0.072, vaporPressure: 3.17 },
  { id: 'C033', iupacName: 'Hexane', formula: 'C6H14', casNumber: '110-54-3', hexColor: '#F0F8FF', opacity: 30, surfaceLuster: 'Glassy', stateAt25C: 'Liquid', density: 0.659, viscosity: 0.294, meltingPoint: -95.3, boilingPoint: 68.7, ghsHazards: 'GHS02-GHS07-GHS09', smellDescription: 'Faint, gasoline-like', riskRating: 5, molarMass: 86.178, category: 'Solvent', specificHeatCapacity: 2.27, surfaceTension: 0.018, vaporPressure: 17.6 },
  { id: 'C034', iupacName: 'Toluene', formula: 'C7H8', casNumber: '108-88-3', hexColor: '#F0F8FF', opacity: 30, surfaceLuster: 'Glassy', stateAt25C: 'Liquid', density: 0.867, viscosity: 0.56, meltingPoint: -95, boilingPoint: 110.6, ghsHazards: 'GHS02-GHS07', smellDescription: 'Sweet, pungent', riskRating: 5, molarMass: 92.141, category: 'Solvent', specificHeatCapacity: 1.7, surfaceTension: 0.028, vaporPressure: 3.8 },
  { id: 'C035', iupacName: 'Dichloromethane', formula: 'CH2Cl2', casNumber: '75-09-2', hexColor: '#F0F8FF', opacity: 40, surfaceLuster: 'Glassy', stateAt25C: 'Liquid', density: 1.326, viscosity: 0.43, meltingPoint: -96.7, boilingPoint: 39.6, ghsHazards: 'GHS06-GHS08', smellDescription: 'Sweet, chloroform-like', riskRating: 6, molarMass: 84.93, category: 'Solvent', specificHeatCapacity: 1.18, surfaceTension: 0.028, vaporPressure: 47.4 },
  { id: 'C036', iupacName: 'Cyclohexane', formula: 'C6H12', casNumber: '110-82-7', hexColor: '#F0F8FF', opacity: 30, surfaceLuster: 'Glassy', stateAt25C: 'Liquid', density: 0.779, viscosity: 0.894, meltingPoint: 6.47, boilingPoint: 80.75, ghsHazards: 'GHS02-GHS07-GHS09', smellDescription: 'Faint, sweet', riskRating: 4, molarMass: 84.162, category: 'Solvent', specificHeatCapacity: 1.83, surfaceTension: 0.025, vaporPressure: 10.3 },
  { id: 'C037', iupacName: 'Ethyl Acetate', formula: 'CH3COOC2H5', casNumber: '141-78-6', hexColor: '#F0F8FF', opacity: 30, surfaceLuster: 'Glassy', stateAt25C: 'Liquid', density: 0.902, viscosity: 0.423, meltingPoint: -83.6, boilingPoint: 77.1, ghsHazards: 'GHS02', smellDescription: 'Sweet, fruity', riskRating: 3, molarMass: 88.106, category: 'Solvent', specificHeatCapacity: 1.93, surfaceTension: 0.024, vaporPressure: 12.6 },
  { id: 'C038', iupacName: 'Chloroform', formula: 'CHCl3', casNumber: '67-66-3', hexColor: '#F0F8FF', opacity: 40, surfaceLuster: 'Glassy', stateAt25C: 'Liquid', density: 1.489, viscosity: 0.537, meltingPoint: -63.5, boilingPoint: 61.2, ghsHazards: 'GHS06', smellDescription: 'Sweet, heavy', riskRating: 7, molarMass: 119.38, category: 'Solvent', specificHeatCapacity: 0.96, surfaceTension: 0.027, vaporPressure: 26.2 },
  { id: 'C039', iupacName: 'Petroleum Ether', formula: 'Mixture', hexColor: '#F0F8FF', opacity: 30, surfaceLuster: 'Glassy', stateAt25C: 'Liquid', density: 0.656, viscosity: 0.3, meltingPoint: -40, boilingPoint: 60, ghsHazards: 'GHS02-GHS07-GHS08', smellDescription: 'Gasoline-like', riskRating: 6, molarMass: 80, category: 'Solvent', specificHeatCapacity: 2.0, surfaceTension: 0.018, vaporPressure: 40.0 },
  { id: 'C040', iupacName: 'Glycerol', formula: 'C3H8O3', casNumber: '56-81-5', hexColor: '#F0F0FF', opacity: 70, surfaceLuster: 'Glassy', stateAt25C: 'Liquid', density: 1.261, viscosity: 1412, meltingPoint: 17.8, boilingPoint: 290, ghsHazards: '', smellDescription: 'Odourless', riskRating: 1, molarMass: 92.094, category: 'Solvent', specificHeatCapacity: 2.43, surfaceTension: 0.063, vaporPressure: 0.0001 },
  { id: 'C041', iupacName: 'Sucrose', formula: 'C12H22O11', casNumber: '57-50-1', hexColor: '#FFFFFF', opacity: 100, surfaceLuster: 'Glassy', stateAt25C: 'Solid', density: 1.587, viscosity: 0, meltingPoint: 186, boilingPoint: 0, ghsHazards: '', smellDescription: 'Odourless', riskRating: 1, molarMass: 342.297, category: 'Organic', specificHeatCapacity: 1.24, surfaceTension: 0.0, vaporPressure: 0.0 },
  { id: 'C042', iupacName: 'Sodium Hypochlorite (12%)', formula: 'NaClO', casNumber: '7681-52-9', hexColor: '#F0F8FF', opacity: 50, surfaceLuster: 'Glassy', stateAt25C: 'Liquid', density: 1.21, viscosity: 0.8, meltingPoint: -16, boilingPoint: 111, ghsHazards: 'GHS05-GHS09', smellDescription: 'Chlorine-like', riskRating: 5, molarMass: 74.442, category: 'Oxidizer', specificHeatCapacity: 3.73, surfaceTension: 0.053, vaporPressure: 2.5 },
];

const REACTIONS = [
  { id: 'R001', reactionType: 'Acid-Base (Neutralization)', balancedEquation: 'HCl + NaOH → NaCl + H₂O', reactantAId: 'C003', reactantBId: 'C007', catalystId: null, productIds: 'C002,C001', deltaH: -57.3, rateOfReaction: 'Instant', gasEvolution: 'None', requiredPPE: 'Gloves, Goggles, Lab Coat', requiredEquipment: 'Beaker, Thermometer, Stirring Rod', failStateNoGloves: 'Skin contact with HCl causes burning sensation and redness', failStateNoGoggles: 'HCl splash causes severe eye irritation and possible corneal damage', failStateNoFumeHood: 'Minimal risk; HCl vapour is low at room temp' },
  { id: 'R002', reactionType: 'Acid-Base', balancedEquation: '2HCl + Na₂CO₃ → 2NaCl + H₂O + CO₂', reactantAId: 'C003', reactantBId: 'C016', catalystId: null, productIds: 'C002,C001,C029', deltaH: -16.7, rateOfReaction: 'Fast', gasEvolution: 'Mild', requiredPPE: 'Gloves, Goggles', requiredEquipment: 'Beaker', failStateNoGloves: 'Acid burns on skin', failStateNoGoggles: 'Acid splash risk to eyes', failStateNoFumeHood: 'CO₂ buildup in poorly ventilated space' },
  { id: 'R003', reactionType: 'Acid-Base (Neutralization)', balancedEquation: 'H₂SO₄ + 2NaOH → Na₂SO₄ + 2H₂O', reactantAId: 'C004', reactantBId: 'C007', catalystId: null, productIds: 'C002,C001', deltaH: -111.3, rateOfReaction: 'Instant', gasEvolution: 'None', requiredPPE: 'Gloves, Goggles, Lab Coat', requiredEquipment: 'Beaker, Thermometer', failStateNoGloves: 'Severe chemical burns from H₂SO₄', failStateNoGoggles: 'Concentrated H₂SO₄ causes permanent eye damage', failStateNoFumeHood: 'Minimal risk at room temp' },
  { id: 'R004', reactionType: 'Redox', balancedEquation: 'Zn + H₂SO₄ → ZnSO₄ + H₂', reactantAId: 'E030', reactantBId: 'C004', catalystId: null, productIds: 'C025,E001', deltaH: -163.2, rateOfReaction: 'Moderate', gasEvolution: 'Mild', requiredPPE: 'Gloves, Goggles', requiredEquipment: 'Beaker, Test Tube', failStateNoGloves: 'Acid burns from H₂SO₄', failStateNoGoggles: 'Acid splash risk', failStateNoFumeHood: 'H₂ gas is flammable - risk of explosion' },
  { id: 'R005', reactionType: 'Precipitation', balancedEquation: 'BaCl₂ + H₂SO₄ → BaSO₄↓ + 2HCl', reactantAId: 'C022', reactantBId: 'C004', catalystId: null, productIds: 'C002,C003', deltaH: -20.0, rateOfReaction: 'Fast', gasEvolution: 'None', requiredPPE: 'Gloves, Goggles', requiredEquipment: 'Beaker', failStateNoGloves: 'Barium compounds are toxic through skin', failStateNoGoggles: 'HCl product splashes eyes', failStateNoFumeHood: 'Minimal risk' },
  { id: 'R006', reactionType: 'Decomposition', balancedEquation: '2H₂O₂ →(MnO₂) 2H₂O + O₂', reactantAId: 'C012', reactantBId: null, catalystId: 'C024', productIds: 'C001,E008', deltaH: -98.0, rateOfReaction: 'Moderate', gasEvolution: 'Vigorous', requiredPPE: 'Gloves, Goggles', requiredEquipment: 'Beaker, Test Tube', failStateNoGloves: 'H₂O₂ causes skin bleaching', failStateNoGoggles: 'Oxygen喷射 and splashing risk', failStateNoFumeHood: 'Oxygen enrichment increases fire risk' },
  { id: 'R007', reactionType: 'Acid-Base', balancedEquation: 'NaHCO₃ + HCl → NaCl + H₂O + CO₂', reactantAId: 'C018', reactantBId: 'C003', catalystId: null, productIds: 'C002,C001,C029', deltaH: -12.0, rateOfReaction: 'Fast', gasEvolution: 'Mild', requiredPPE: 'Gloves', requiredEquipment: 'Beaker', failStateNoGloves: 'Mild acid irritation', failStateNoGoggles: 'Acid splash risk', failStateNoFumeHood: 'CO₂ buildup possible' },
  { id: 'R008', reactionType: 'Precipitation', balancedEquation: 'AgNO₃ + NaCl → AgCl↓ + NaNO₃', reactantAId: 'C020', reactantBId: 'C002', catalystId: null, productIds: 'C002,C002', deltaH: -65.5, rateOfReaction: 'Instant', gasEvolution: 'None', requiredPPE: 'Gloves, Goggles', requiredEquipment: 'Beaker', failStateNoGloves: 'Silver nitrate stains skin brown/black', failStateNoGoggles: 'Silver nitrate causes eye damage', failStateNoFumeHood: 'No significant risk' },
  { id: 'R009', reactionType: 'Acid-Base', balancedEquation: 'Na₂CO₃ + H₂SO₄ → Na₂SO₄ + H₂O + CO₂', reactantAId: 'C016', reactantBId: 'C004', catalystId: null, productIds: 'C002,C001,C029', deltaH: -22.1, rateOfReaction: 'Fast', gasEvolution: 'Mild', requiredPPE: 'Gloves, Goggles', requiredEquipment: 'Beaker', failStateNoGloves: 'Acid burns from H₂SO₄', failStateNoGoggles: 'Acid splash risk', failStateNoFumeHood: 'CO₂ buildup possible' },
  { id: 'R010', reactionType: 'Redox', balancedEquation: 'Fe + CuSO₄ → FeSO₄ + Cu', reactantAId: 'E026', reactantBId: 'C013', catalystId: null, productIds: 'C026,E029', deltaH: -151.0, rateOfReaction: 'Slow', gasEvolution: 'None', requiredPPE: 'Gloves', requiredEquipment: 'Beaker', failStateNoGloves: 'CuSO₄ is a skin irritant', failStateNoGoggles: 'CuSO₄ splash risk to eyes', failStateNoFumeHood: 'No significant risk' },
  { id: 'R011', reactionType: 'Acid-Base', balancedEquation: 'CH₃COOH + NaOH → CH₃COONa + H₂O', reactantAId: 'C006', reactantBId: 'C007', catalystId: null, productIds: 'C002,C001', deltaH: -57.3, rateOfReaction: 'Instant', gasEvolution: 'None', requiredPPE: 'Gloves, Goggles', requiredEquipment: 'Beaker, Thermometer', failStateNoGloves: 'Acetic acid and NaOH both cause skin burns', failStateNoGoggles: 'Serious eye damage risk', failStateNoFumeHood: 'Acetic acid vapour irritating' },
  { id: 'R012', reactionType: 'Redox', balancedEquation: '2KMnO₄ + 5H₂O₂ + 3H₂SO₄ → 2MnSO₄ + K₂SO₄ + 5O₂ + 8H₂O', reactantAId: 'C015', reactantBId: 'C012', catalystId: 'C004', productIds: 'C002,C002,E008,C001', deltaH: -726.0, rateOfReaction: 'Fast', gasEvolution: 'Vigorous', requiredPPE: 'Gloves, Goggles, Lab Coat', requiredEquipment: 'Beaker, Fume Hood', failStateNoGloves: 'KMnO₄ and H₂SO₄ cause severe burns', failStateNoGoggles: 'Vigorous oxygen eruption can splash reagents into eyes', failStateNoFumeHood: 'Oxygen gas and acid vapours - fire and inhalation hazard' },
  { id: 'R013', reactionType: 'Precipitation', balancedEquation: 'Pb(NO₃)₂ + 2KI → PbI₂↓ + 2KNO₃', reactantAId: 'C021', reactantBId: 'C019', catalystId: null, productIds: 'C019,C019', deltaH: -52.0, rateOfReaction: 'Instant', gasEvolution: 'None', requiredPPE: 'Gloves, Goggles', requiredEquipment: 'Beaker', failStateNoGloves: 'Lead compounds are toxic through skin absorption', failStateNoGoggles: 'Lead and iodide compounds damage eyes', failStateNoFumeHood: 'Minimal risk at room temp' },
  { id: 'R014', reactionType: 'Acid-Base', balancedEquation: '2HCl + CaCO₃ → CaCl₂ + H₂O + CO₂', reactantAId: 'C003', reactantBId: 'C017', catalystId: null, productIds: 'C023,C001,C029', deltaH: -17.8, rateOfReaction: 'Fast', gasEvolution: 'Mild', requiredPPE: 'Gloves, Goggles', requiredEquipment: 'Beaker', failStateNoGloves: 'HCl causes skin burns', failStateNoGoggles: 'Acid splash risk to eyes', failStateNoFumeHood: 'CO₂ buildup possible' },
  { id: 'R015', reactionType: 'Acid-Base', balancedEquation: 'NH₃ + HCl → NH₄Cl', reactantAId: 'C008', reactantBId: 'C003', catalystId: null, productIds: 'C002', deltaH: -176.0, rateOfReaction: 'Instant', gasEvolution: 'Mild', requiredPPE: 'Gloves, Goggles, Lab Coat', requiredEquipment: 'Beaker, Fume Hood', failStateNoGloves: 'HCl and NH₃ both cause skin irritation', failStateNoGoggles: 'NH₃ gas severely irritates eyes', failStateNoFumeHood: 'NH₃ gas is toxic and pungent - requires ventilation' },
  { id: 'R016', reactionType: 'Displacement', balancedEquation: '2Na + 2H₂O → 2NaOH + H₂', reactantAId: 'E011', reactantBId: 'C001', catalystId: null, productIds: 'C007,E001', deltaH: -184.0, rateOfReaction: 'Vigorous', gasEvolution: 'Vigorous', requiredPPE: 'Gloves, Goggles, Lab Coat, Face Shield', requiredEquipment: 'Beaker, Fume Hood, Safety Screen', failStateNoGloves: 'Na metal reacts with skin moisture causing severe burns', failStateNoGoggles: 'Na reaction is explosive - eye damage risk', failStateNoFumeHood: 'H₂ gas is flammable and explosive' },
  { id: 'R017', reactionType: 'Displacement', balancedEquation: '2K + 2H₂O → 2KOH + H₂', reactantAId: 'E019', reactantBId: 'C001', catalystId: null, productIds: 'C007,E001', deltaH: -196.0, rateOfReaction: 'Vigorous', gasEvolution: 'Vigorous', requiredPPE: 'Gloves, Goggles, Lab Coat, Face Shield', requiredEquipment: 'Beaker, Fume Hood, Safety Screen', failStateNoGloves: 'K metal is extremely reactive with skin moisture', failStateNoGoggles: 'K reaction is violently explosive', failStateNoFumeHood: 'H₂ gas explodes - severe fire hazard' },
  { id: 'R018', reactionType: 'Acid-Base', balancedEquation: 'H₂SO₄ + CuO → CuSO₄ + H₂O', reactantAId: 'C004', reactantBId: 'C028', catalystId: null, productIds: 'C013,C001', deltaH: -85.0, rateOfReaction: 'Slow', gasEvolution: 'None', requiredPPE: 'Gloves, Goggles', requiredEquipment: 'Beaker, Bunsen Burner', failStateNoGloves: 'H₂SO₄ causes severe skin burns', failStateNoGoggles: 'Concentrated acid splash hazard', failStateNoFumeHood: 'Minimal risk' },
  { id: 'R019', reactionType: 'Precipitation', balancedEquation: 'CuSO₄ + 2NaOH → Cu(OH)₂↓ + Na₂SO₄', reactantAId: 'C013', reactantBId: 'C007', catalystId: null, productIds: 'C002', deltaH: -77.0, rateOfReaction: 'Fast', gasEvolution: 'None', requiredPPE: 'Gloves, Goggles', requiredEquipment: 'Beaker', failStateNoGloves: 'NaOH causes caustic burns', failStateNoGoggles: 'CuSO₄ and NaOH splash risk', failStateNoFumeHood: 'Minimal risk' },
  { id: 'R020', reactionType: 'Redox', balancedEquation: 'Mg + 2HCl → MgCl₂ + H₂', reactantAId: 'E012', reactantBId: 'C003', catalystId: null, productIds: 'C002,E001', deltaH: -468.0, rateOfReaction: 'Fast', gasEvolution: 'Mild', requiredPPE: 'Gloves, Goggles', requiredEquipment: 'Beaker, Test Tube', failStateNoGloves: 'HCl causes skin burns', failStateNoGoggles: 'Acid splash risk to eyes', failStateNoFumeHood: 'H₂ gas is flammable' },
];

const APPARATUS = [
  { id: 'A001', name: 'Test Tube', category: 'Glassware', heightCm: 15, widthCm: 1.5, depthCm: 1.5, maxVolumeML: 20, maxWeightG: 50, constructionMaterial: 'Borosilicate 3.3', thermalFailurePoint: 560, interactionType: 'Container', description: 'Standard round-bottom test tube for heating and mixing small samples' },
  { id: 'A002', name: 'Beaker (50mL)', category: 'Glassware', heightCm: 6, widthCm: 4, depthCm: 4, maxVolumeML: 50, maxWeightG: 100, constructionMaterial: 'Borosilicate 3.3', thermalFailurePoint: 560, interactionType: 'Container', description: 'Small beaker for basic mixing and heating' },
  { id: 'A003', name: 'Beaker (100mL)', category: 'Glassware', heightCm: 7, widthCm: 5, depthCm: 5, maxVolumeML: 100, maxWeightG: 200, constructionMaterial: 'Borosilicate 3.3', thermalFailurePoint: 560, interactionType: 'Container', description: 'Standard beaker for general lab work' },
  { id: 'A004', name: 'Beaker (250mL)', category: 'Glassware', heightCm: 9, widthCm: 7, depthCm: 7, maxVolumeML: 250, maxWeightG: 500, constructionMaterial: 'Borosilicate 3.3', thermalFailurePoint: 560, interactionType: 'Container', description: 'Medium beaker for larger reactions' },
  { id: 'A005', name: 'Beaker (500mL)', category: 'Glassware', heightCm: 11, widthCm: 8, depthCm: 8, maxVolumeML: 500, maxWeightG: 1000, constructionMaterial: 'Borosilicate 3.3', thermalFailurePoint: 560, interactionType: 'Container', description: 'Large beaker for bulk mixing' },
  { id: 'A006', name: 'Beaker (1000mL)', category: 'Glassware', heightCm: 14, widthCm: 10, depthCm: 10, maxVolumeML: 1000, maxWeightG: 2000, constructionMaterial: 'Borosilicate 3.3', thermalFailurePoint: 560, interactionType: 'Container', description: 'Extra-large beaker for industrial-scale reactions' },
  { id: 'A007', name: 'Erlenmeyer Flask (250mL)', category: 'Glassware', heightCm: 15, widthCm: 8, depthCm: 8, maxVolumeML: 250, maxWeightG: 500, constructionMaterial: 'Borosilicate 3.3', thermalFailurePoint: 560, interactionType: 'Container', description: 'Conical flask ideal for swirling without splashing' },
  { id: 'A008', name: 'Erlenmeyer Flask (500mL)', category: 'Glassware', heightCm: 18, widthCm: 10, depthCm: 10, maxVolumeML: 500, maxWeightG: 1000, constructionMaterial: 'Borosilicate 3.3', thermalFailurePoint: 560, interactionType: 'Container', description: 'Large conical flask' },
  { id: 'A009', name: 'Round-Bottom Flask (250mL)', category: 'Glassware', heightCm: 14, widthCm: 8, depthCm: 8, maxVolumeML: 250, maxWeightG: 500, constructionMaterial: 'Borosilicate 3.3', thermalFailurePoint: 560, interactionType: 'Container', description: 'For uniform heating and distillation' },
  { id: 'A010', name: 'Florence Flask (500mL)', category: 'Glassware', heightCm: 18, widthCm: 10, depthCm: 10, maxVolumeML: 500, maxWeightG: 1000, constructionMaterial: 'Borosilicate 3.3', thermalFailurePoint: 560, interactionType: 'Container', description: 'Large round-bottom flask for boiling' },
  { id: 'A011', name: 'Graduated Cylinder (10mL)', category: 'Measurement', heightCm: 15, widthCm: 2, depthCm: 2, maxVolumeML: 10, maxWeightG: 30, constructionMaterial: 'Borosilicate 3.3', thermalFailurePoint: 560, interactionType: 'Measurement', description: 'Precise volume measurement for small quantities' },
  { id: 'A012', name: 'Graduated Cylinder (100mL)', category: 'Measurement', heightCm: 30, widthCm: 4, depthCm: 4, maxVolumeML: 100, maxWeightG: 200, constructionMaterial: 'Borosilicate 3.3', thermalFailurePoint: 560, interactionType: 'Measurement', description: 'Precise volume measurement' },
  { id: 'A013', name: 'Volumetric Flask (100mL)', category: 'Measurement', heightCm: 16, widthCm: 5, depthCm: 5, maxVolumeML: 100, maxWeightG: 200, constructionMaterial: 'Borosilicate 3.3', thermalFailurePoint: 560, interactionType: 'Measurement', description: 'For preparing standard solutions' },
  { id: 'A014', name: 'Burette (50mL)', category: 'Measurement', heightCm: 60, widthCm: 3, depthCm: 3, maxVolumeML: 50, maxWeightG: 100, constructionMaterial: 'Borosilicate 3.3', thermalFailurePoint: 560, interactionType: 'Measurement', description: 'For precise titration' },
  { id: 'A015', name: 'Pipette (10mL)', category: 'Measurement', heightCm: 35, widthCm: 1, depthCm: 1, maxVolumeML: 10, maxWeightG: 20, constructionMaterial: 'Borosilicate 3.3', thermalFailurePoint: 560, interactionType: 'Measurement', description: 'For precise liquid transfer' },
  { id: 'A016', name: 'Watch Glass', category: 'Glassware', heightCm: 0.5, widthCm: 8, depthCm: 8, maxVolumeML: 0, maxWeightG: 50, constructionMaterial: 'Borosilicate 3.3', thermalFailurePoint: 560, interactionType: 'Container', description: 'For evaporating and covering beakers' },
  { id: 'A017', name: 'Evaporating Dish', category: 'Glassware', heightCm: 3, widthCm: 10, depthCm: 10, maxVolumeML: 50, maxWeightG: 100, constructionMaterial: 'Porcelain', thermalFailurePoint: 1400, interactionType: 'Container', description: 'For evaporating solutions to dryness' },
  { id: 'A018', name: 'Crucible with Lid', category: 'Glassware', heightCm: 5, widthCm: 4, depthCm: 4, maxVolumeML: 15, maxWeightG: 50, constructionMaterial: 'Porcelain', thermalFailurePoint: 1400, interactionType: 'Container', description: 'For high-temperature heating and ignition' },
  { id: 'A019', name: 'Funnel', category: 'Glassware', heightCm: 10, widthCm: 6, depthCm: 6, maxVolumeML: 0, maxWeightG: 50, constructionMaterial: 'Borosilicate 3.3', thermalFailurePoint: 560, interactionType: 'Support', description: 'For filtering and guiding liquids' },
  { id: 'A020', name: 'Thermometer (-10 to 110°C)', category: 'Measurement', heightCm: 25, widthCm: 1, depthCm: 1, maxVolumeML: 0, maxWeightG: 0, constructionMaterial: 'Glass', thermalFailurePoint: 500, interactionType: 'Measurement', description: 'For measuring temperature in liquids' },
  { id: 'A021', name: 'Bunsen Burner', category: 'Heating', heightCm: 15, widthCm: 8, depthCm: 8, maxVolumeML: 0, maxWeightG: 0, constructionMaterial: 'Brass/Steel', thermalFailurePoint: 1500, interactionType: 'Heating', description: 'Gas burner for heating, sterilization, and combustion' },
  { id: 'A022', name: 'Hot Plate', category: 'Heating', heightCm: 10, widthCm: 20, depthCm: 20, maxVolumeML: 0, maxWeightG: 5000, constructionMaterial: 'Steel', thermalFailurePoint: 800, interactionType: 'Heating', description: 'Electric heating surface for beakers and flasks' },
  { id: 'A023', name: 'Magnetic Stirrer', category: 'Heating', heightCm: 8, widthCm: 15, depthCm: 15, maxVolumeML: 0, maxWeightG: 2000, constructionMaterial: 'Steel', thermalFailurePoint: 500, interactionType: 'Heating', description: 'Combined heating and magnetic stirring' },
  { id: 'A024', name: 'Ring Stand', category: 'Support', heightCm: 60, widthCm: 15, depthCm: 15, maxVolumeML: 0, maxWeightG: 2000, constructionMaterial: 'Steel', thermalFailurePoint: 1500, interactionType: 'Support', description: 'Support structure for clamps and apparatus' },
  { id: 'A025', name: 'Clamp', category: 'Support', heightCm: 10, widthCm: 3, depthCm: 3, maxVolumeML: 0, maxWeightG: 500, constructionMaterial: 'Steel', thermalFailurePoint: 1500, interactionType: 'Support', description: 'For securing glassware to ring stands' },
  { id: 'A026', name: 'Wire Gauze', category: 'Support', heightCm: 0.2, widthCm: 10, depthCm: 10, maxVolumeML: 0, maxWeightG: 200, constructionMaterial: 'Steel', thermalFailurePoint: 1400, interactionType: 'Support', description: 'For supporting beakers on ring stands' },
  { id: 'A027', name: 'Safety Goggles', category: 'Safety', heightCm: 5, widthCm: 15, depthCm: 5, maxVolumeML: 0, maxWeightG: 0, constructionMaterial: 'Polycarbonate', thermalFailurePoint: 200, interactionType: 'Safety', description: 'Impact and chemical splash protection for eyes' },
  { id: 'A028', name: 'Nitrile Gloves', category: 'Safety', heightCm: 25, widthCm: 12, depthCm: 0.1, maxVolumeML: 0, maxWeightG: 0, constructionMaterial: 'Nitrile', thermalFailurePoint: 200, interactionType: 'Safety', description: 'Chemical-resistant hand protection' },
  { id: 'A029', name: 'Lab Coat', category: 'Safety', heightCm: 80, widthCm: 50, depthCm: 3, maxVolumeML: 0, maxWeightG: 0, constructionMaterial: 'Cotton', thermalFailurePoint: 200, interactionType: 'Safety', description: 'Full-body splash protection' },
  { id: 'A030', name: 'Fume Hood', category: 'Safety', heightCm: 200, widthCm: 150, depthCm: 100, maxVolumeML: 0, maxWeightG: 0, constructionMaterial: 'Steel/Glass', thermalFailurePoint: 800, interactionType: 'Safety', description: 'Ventilated enclosure for hazardous experiments' },
  { id: 'A031', name: 'Wash Bottle', category: 'Glassware', heightCm: 20, widthCm: 5, depthCm: 5, maxVolumeML: 500, maxWeightG: 500, constructionMaterial: 'Polyethylene', thermalFailurePoint: 120, interactionType: 'Container', description: 'Squeeze bottle for distilled water rinsing' },
  { id: 'A032', name: 'Dropper/Pipette', category: 'Measurement', heightCm: 15, widthCm: 1, depthCm: 1, maxVolumeML: 1, maxWeightG: 5, constructionMaterial: 'Glass', thermalFailurePoint: 500, interactionType: 'Measurement', description: 'For transferring small liquid volumes' },
  { id: 'A033', name: 'Spatula', category: 'Support', heightCm: 20, widthCm: 2, depthCm: 1, maxVolumeML: 0, maxWeightG: 50, constructionMaterial: 'Stainless Steel', thermalFailurePoint: 1400, interactionType: 'Support', description: 'For transferring solid chemicals' },
  { id: 'A034', name: 'Mortar and Pestle', category: 'Support', heightCm: 8, widthCm: 8, depthCm: 8, maxVolumeML: 50, maxWeightG: 200, constructionMaterial: 'Porcelain', thermalFailurePoint: 1400, interactionType: 'Support', description: 'For grinding and mixing solid substances' },
  { id: 'A035', name: 'Tongs', category: 'Support', heightCm: 25, widthCm: 5, depthCm: 3, maxVolumeML: 0, maxWeightG: 200, constructionMaterial: 'Steel', thermalFailurePoint: 1400, interactionType: 'Support', description: 'For safely handling hot glassware' },
  { id: 'A036', name: 'Test Tube Rack', category: 'Support', heightCm: 10, widthCm: 15, depthCm: 8, maxVolumeML: 0, maxWeightG: 500, constructionMaterial: 'Polyethylene', thermalFailurePoint: 120, interactionType: 'Support', description: 'For holding multiple test tubes' },
  { id: 'A037', name: 'Bunsen Burner Lighter', category: 'Heating', heightCm: 15, widthCm: 3, depthCm: 3, maxVolumeML: 0, maxWeightG: 0, constructionMaterial: 'Steel', thermalFailurePoint: 500, interactionType: 'Heating', description: 'Flint striker for igniting Bunsen burners' },
  { id: 'A038', name: 'Stirring Rod', category: 'Support', heightCm: 25, widthCm: 0.5, depthCm: 0.5, maxVolumeML: 0, maxWeightG: 0, constructionMaterial: 'Borosilicate 3.3', thermalFailurePoint: 560, interactionType: 'Support', description: 'Glass rod for stirring solutions' },
  { id: 'A039', name: 'pH Meter', category: 'Measurement', heightCm: 15, widthCm: 3, depthCm: 3, maxVolumeML: 0, maxWeightG: 0, constructionMaterial: 'Plastic/Glass', thermalFailurePoint: 100, interactionType: 'Measurement', description: 'Digital pH measurement device' },
  { id: 'A040', name: 'Analytical Balance', category: 'Measurement', heightCm: 10, widthCm: 20, depthCm: 30, maxVolumeML: 0, maxWeightG: 200, constructionMaterial: 'Steel/Aluminium', thermalFailurePoint: 200, interactionType: 'Measurement', description: 'Precision mass measurement to 0.001g' },
];

const GHS_HAZARDS = [
  { id: 'GHS01', hazardClass: 'Explosive', iconDescription: 'Exploding bomb', colorCode: '#E00000', severityLevel: 5, gameplayEffect: 'Screen shake, explosion particle system, 3-second stun, ear damage debuff' },
  { id: 'GHS02', hazardClass: 'Flammable', iconDescription: 'Flame', colorCode: '#FF6600', severityLevel: 4, gameplayEffect: 'Fire particles, ignition chance, burn damage over time' },
  { id: 'GHS03', hazardClass: 'Oxidizing', iconDescription: 'Flame over circle', colorCode: '#FFAA00', severityLevel: 4, gameplayEffect: 'Intensifies nearby fires, increases burn damage' },
  { id: 'GHS04', hazardClass: 'Compressed Gas', iconDescription: 'Gas cylinder', colorCode: '#00AA00', severityLevel: 3, gameplayEffect: 'Pressure buildup, possible explosion if contained' },
  { id: 'GHS05', hazardClass: 'Corrosive', iconDescription: 'Test tubes pouring on hand and surface', colorCode: '#8B0000', severityLevel: 5, gameplayEffect: 'Chemical burn damage, surface corrosion visual' },
  { id: 'GHS06', hazardClass: 'Toxic', iconDescription: 'Skull and crossbones', colorCode: '#000000', severityLevel: 5, gameplayEffect: 'Immediate health damage, requires fume hood' },
  { id: 'GHS07', hazardClass: 'Harmful', iconDescription: 'Exclamation mark', colorCode: '#FF9900', severityLevel: 2, gameplayEffect: 'Gradual health damage, mild irritation' },
  { id: 'GHS08', hazardClass: 'Health Hazard', iconDescription: 'Person with damaged chest', colorCode: '#990099', severityLevel: 4, gameplayEffect: 'Long-term health effects, organ damage debuff' },
  { id: 'GHS09', hazardClass: 'Environmental', iconDescription: 'Dead tree and fish', colorCode: '#006600', severityLevel: 3, gameplayEffect: 'Environmental contamination, spill cleanup required' },
];

async function main() {
  console.log('🌱 Seeding database...');

  // Seed substances
  const allSubstances = [...ELEMENTS, ...COMPOUNDS];
  for (const sub of allSubstances) {
    await prisma.substance.upsert({
      where: { id: sub.id },
      update: sub,
      create: sub,
    });
  }
  console.log(`✅ Seeded ${allSubstances.length} substances`);

  // Seed apparatus
  for (const app of APPARATUS) {
    await prisma.apparatus.upsert({
      where: { id: app.id },
      update: app,
      create: app,
    });
  }
  console.log(`✅ Seeded ${APPARATUS.length} apparatus`);

  // Seed reactions
  for (const rxn of REACTIONS) {
    await prisma.reaction.upsert({
      where: { id: rxn.id },
      update: rxn,
      create: rxn,
    });
  }
  console.log(`✅ Seeded ${REACTIONS.length} reactions`);

  // Seed GHS hazards
  for (const ghs of GHS_HAZARDS) {
    await prisma.gHSHazard.upsert({
      where: { id: ghs.id },
      update: ghs,
      create: ghs,
    });
  }
  console.log(`✅ Seeded ${GHS_HAZARDS.length} GHS hazards`);

  console.log('🎉 Database seeding complete!');
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
